In [1]:
# === LOCAL RUN OVERRIDE (khong co trong ban Colab) ===
import os
from dotenv import load_dotenv
load_dotenv(r"d:\VinUni-AI20K\K4-Track3-Lab19-2A202601941-NguyenHoangVu\.env")
os.environ["OUTPUT_DIR"] = os.environ.get("LAB_OUTPUT_DIR", r"d:\VinUni-AI20K\K4-Track3-Lab19-2A202601941-NguyenHoangVu\outputs")
os.environ["REPORTS_DIR"] = os.environ.get("LAB_REPORTS_DIR", r"d:\VinUni-AI20K\K4-Track3-Lab19-2A202601941-NguyenHoangVu\reports")
os.environ["GOLDEN_SOURCE_CSV"] = r"d:\VinUni-AI20K\K4-Track3-Lab19-2A202601941-NguyenHoangVu\data\graphrag_golden_50_first5000.csv"
# llama3-70b-8192 da bi Groq khai tu; key nay chi con gpt-oss / qwen.
os.environ["GROQ_MODEL"] = "openai/gpt-oss-120b"
# Golden set cua giang vien neo vao dung chi so dong goc -> khong duoc xoa bai trung lap gan.
os.environ["NEAR_DEDUP_APPLY"] = "0"
print("Local run: model =", os.environ["GROQ_MODEL"])

Local run: model = openai/gpt-oss-120b

# 🚀 LAB GUIDE — PRODUCTION-GRADE GRAPHRAG VS FLAT RAG

**Thời lượng:** 120 phút  
**Môi trường:** Google Colab (T4 GPU khuyến nghị) + Neo4j AuraDB  
**Dữ liệu:** HackerNoon Tech Company News Data Dump (bản thu gọn do giảng viên cung cấp)  
**Công cụ:** Học viên được dùng AI Coding Agent, nhưng phải tự thiết kế, kiểm thử và giải thích logic.

## 🎯 Mục tiêu
1. Xây dựng Hybrid GraphRAG end-to-end.
2. Xử lý Coreference Resolution, Entity Resolution và Super-node Mitigation.
3. Bulk insert bằng `UNWIND`, không insert từng row.
4. So sánh Flat RAG và GraphRAG bằng Golden Dataset + LLM-as-a-Judge.
5. Đo quality, latency và token usage.
6. Giải thích kiến trúc và failure modes.

> Notebook là **reference lab guide**: có code khung chạy được nhưng vẫn yêu cầu học viên thay prompt/threshold/retrieval policy và thuyết minh lựa chọn.

## ⏳ Timeline

| Phút | Nội dung |
|---|---|
| 00–15 | Setup, load, dedup, chunk, coreference |
| 15–45 | NER/RE, entity resolution, Neo4j bulk insert |
| 45–75 | Flat RAG, graph traversal, hybrid retrieval |
| 75–105 | Golden Dataset, LLM-as-a-Judge, comparison |
| 105–120 | Failure-mode tests, bonus, export, thuyết minh |

### Scale guard
Trong lab 2 giờ, không nên gửi toàn bộ 350MB qua LLM. Mặc định dùng subset:
- `LAB_MAX_ARTICLES = 1500`
- `LAB_MAX_CHUNKS = 3000`
- `EXTRACTION_MAX_CHUNKS = 400`

Kiến trúc phải scale được; volume trong giờ lab chỉ dùng để chứng minh pipeline.

# PHẦN 1 — SETUP & PREPROCESSING

### Secrets trên Colab
Tạo:
- `NEO4J_URI`, `NEO4J_USER`, `NEO4J_PASSWORD`
- `GROQ_API_KEY`, `GROQ_MODEL`
- `HF_TOKEN` để stream dataset từ Hugging Face
- cho judge: `JUDGE_PROVIDER`, `JUDGE_MODEL`, và `OPENAI_API_KEY` nếu dùng OpenAI

Không hard-code API key vào notebook nộp bài.

In [2]:
#@title 1.1 — Install
# (Local run: thu vien da cai san trong moi truong Python cua may.)
# %pip -q install neo4j pandas numpy pyarrow sentence-transformers faiss-cpu groq openai tqdm networkx spacy datasets langchain-community llama-index

In [3]:
#@title 1.2 — Imports & config
import os, re, json, time, random, hashlib, unicodedata
from pathlib import Path
from collections import defaultdict, Counter, deque
from difflib import SequenceMatcher

import numpy as np
import pandas as pd
from tqdm.auto import tqdm
from neo4j import GraphDatabase
from sentence_transformers import SentenceTransformer
import faiss

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
pd.set_option("display.max_colwidth", 120)

def get_secret(name, default=None):
    try:
        from google.colab import userdata
        value = userdata.get(name)
        if value is not None:
            return value
    except Exception:
        pass
    return os.environ.get(name, default)

NEO4J_URI = get_secret("NEO4J_URI", "")
NEO4J_USER = get_secret("NEO4J_USER", "neo4j")
NEO4J_PASSWORD = get_secret("NEO4J_PASSWORD", "")
# Aura dat ten database theo instance id, khong phai "neo4j".
# De trong -> driver dung home database cua tai khoan, chay duoc voi moi instance.
NEO4J_DATABASE = get_secret("NEO4J_DATABASE", "") or None

GROQ_API_KEY = get_secret("GROQ_API_KEY", "")
GROQ_MODEL = get_secret("GROQ_MODEL", "")

JUDGE_PROVIDER = get_secret("JUDGE_PROVIDER", "openai").lower()
JUDGE_MODEL = get_secret("JUDGE_MODEL", "")
OPENAI_API_KEY = get_secret("OPENAI_API_KEY", "")
HF_TOKEN = get_secret("HF_TOKEN", "")

DATA_PATH = "/content/hackernoon_subset.csv"
LAB_MAX_ARTICLES = 1500
LAB_MAX_CHUNKS = 3000
EXTRACTION_MAX_CHUNKS = 400
CHUNK_WORDS = 220
CHUNK_OVERLAP_WORDS = 40

# Số chunk mỗi request LLM. Bản tin ngắn (headline + description) nên gộp được nhiều chunk/request.
COREF_BATCH = 5
EXTRACT_BATCH = 4

# Dump tin tức thường để phần lớn thông tin ở headline; nếu chỉ embed phần body
# thì cả Flat RAG lẫn NER/RE đều mất thực thể chính.
PREPEND_TITLE_TO_TEXT = True

# Nếu giảng viên phát Golden Dataset riêng, trỏ vào đây (CSV có id/group/question/reference_answer).
GOLDEN_SOURCE_CSV = get_secret("GOLDEN_SOURCE_CSV", "")

# --- Thư mục bài nộp (Colab). Đổi bằng Colab Secrets nếu cần. ---
OUTPUT_DIR = Path(get_secret("OUTPUT_DIR", "/content/outputs"))
REPORTS_DIR = Path(get_secret("REPORTS_DIR", "/content/reports"))
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

# RUN_STATE gom số liệu thật của từng bước để sinh báo cáo thuyết minh ở Phần 5.
# Colab dung /content; khi chay ngoai Colab thi lay thu muc canh outputs/.
WORK_DIR = Path("/content") if Path("/content").exists() else OUTPUT_DIR.parent
WORK_DIR.mkdir(parents=True, exist_ok=True)

RUN_STATE = {}

STUDENT_NAME = "Nguyen Hoang Vu"
STUDENT_ID = "2A202601941"

def missing_secrets():
    need = {
        "NEO4J_URI": NEO4J_URI, "NEO4J_PASSWORD": NEO4J_PASSWORD,
        "GROQ_API_KEY": GROQ_API_KEY, "GROQ_MODEL": GROQ_MODEL,
        "HF_TOKEN": HF_TOKEN, "JUDGE_MODEL": JUDGE_MODEL,
    }
    if JUDGE_PROVIDER == "openai":
        need["OPENAI_API_KEY"] = OPENAI_API_KEY
    return [k for k, v in need.items() if not v]

_missing = missing_secrets()
print("Secrets còn thiếu:", _missing if _missing else "không")
print("OUTPUT_DIR:", OUTPUT_DIR, "| REPORTS_DIR:", REPORTS_DIR)
print("Judge:", JUDGE_PROVIDER, JUDGE_MODEL, "| Groq model:", GROQ_MODEL)

C:\Users\Vu\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Secrets còn thiếu: không
OUTPUT_DIR: d:\VinUni-AI20K\K4-Track3-Lab19-2A202601941-NguyenHoangVu\outputs | REPORTS_DIR: d:\VinUni-AI20K\K4-Track3-Lab19-2A202601941-NguyenHoangVu\reports
Judge: openai gpt-4o-mini | Groq model: openai/gpt-oss-120b

In [4]:
# === LOCAL RUN OVERRIDE: scale cho dung Golden Dataset cua giang vien ===
DATA_PATH = r"d:\VinUni-AI20K\K4-Track3-Lab19-2A202601941-NguyenHoangVu\data\hackernoon_subset.csv"
LAB_MAX_ARTICLES = None       # nap dung 5000 dong dau, khong lay mau ngau nhien
LAB_MAX_CHUNKS = None         # index toan bo chunk cho Flat RAG
EXTRACTION_MAX_CHUNKS = None  # trich xuat KG tren toan bo chunk
COREF_BATCH = 8
EXTRACT_BATCH = 8
STUDENT_NAME = "Nguyen Hoang Vu"
STUDENT_ID = "2A202601941"
print("Override:", DATA_PATH, LAB_MAX_ARTICLES, EXTRACTION_MAX_CHUNKS)

Override: d:\VinUni-AI20K\K4-Track3-Lab19-2A202601941-NguyenHoangVu\data\hackernoon_subset.csv None None

## 1.3 — Download HackerNoon Dataset bằng Hugging Face Streaming

Cell dưới đây stream trực tiếp dataset **`HackerNoon/tech-company-news-data-dump`** và ghi dần ra CSV, nên không cần tải toàn bộ dataset vào RAM.

### Hai cơ chế giới hạn

- `LIMIT_ROWS`: số dòng tối đa.
- `LIMIT_MB`: dung lượng file tối đa.
- `PRIORITIZE_MB = True`: ưu tiên dừng theo dung lượng MB.
- `PRIORITIZE_MB = False`: thanh tiến trình theo số dòng, nhưng **vẫn giữ hard-stop `LIMIT_ROWS`**.

### Lưu ý

- Đặt `HF_TOKEN` trong **Colab Secrets**, không hard-code token vào notebook.
- Nếu dataset yêu cầu quyền truy cập/gated access, hãy mở trang dataset trên Hugging Face và hoàn tất bước **Agree/Request access** trước.
- Sau khi cell hoàn tất, `DATA_PATH` mặc định đã trỏ tới `/content/hackernoon_subset.csv`, nên cell loader kế tiếp có thể chạy trực tiếp.

In [5]:
#@title 1.3 — Nguon du lieu
# (Local run: 5000 dong dau cua HackerNoon dump da duoc stream san ra data/.)
import os
DATA_PATH = r"d:\VinUni-AI20K\K4-Track3-Lab19-2A202601941-NguyenHoangVu\data\hackernoon_subset.csv"
print('DATA_PATH =', DATA_PATH, '| size MB =', round(os.path.getsize(DATA_PATH)/1e6, 2))

DATA_PATH = d:\VinUni-AI20K\K4-Track3-Lab19-2A202601941-NguyenHoangVu\data\hackernoon_subset.csv | size MB = 3.07

In [6]:
#@title 1.4 — Neo4j connection + schema
driver = None

def connect_neo4j():
    global driver
    if not NEO4J_URI or not NEO4J_PASSWORD:
        raise ValueError("Thiếu Neo4j secrets.")
    driver = GraphDatabase.driver(
        NEO4J_URI,
        auth=(NEO4J_USER, NEO4J_PASSWORD),
    )
    driver.verify_connectivity()
    with driver.session(database=NEO4J_DATABASE) as s:
        db = s.run("CALL db.info() YIELD name RETURN name").single()["name"]
    print(f"✅ Neo4j connected (database = {db}).")

def run_cypher(query, **params):
    if driver is None:
        raise RuntimeError("Hãy chạy connect_neo4j() trước.")
    with driver.session(database=NEO4J_DATABASE) as session:
        result = session.run(query, **params)
        rows = [r.data() for r in result]
        result.consume()
    return rows

def setup_graph_schema():
    for stmt in [
        """
        CREATE CONSTRAINT entity_id IF NOT EXISTS
        FOR (n:Entity) REQUIRE n.id IS UNIQUE
        """,
        """
        CREATE INDEX entity_name_norm IF NOT EXISTS
        FOR (n:Entity) ON (n.name_norm)
        """,
        """
        CREATE INDEX company_name_norm IF NOT EXISTS
        FOR (n:Company) ON (n.name_norm)
        """,
        """
        CREATE INDEX person_name_norm IF NOT EXISTS
        FOR (n:Person) ON (n.name_norm)
        """,
        """
        CREATE INDEX technology_name_norm IF NOT EXISTS
        FOR (n:Technology) ON (n.name_norm)
        """,
    ]:
        run_cypher(stmt)
    print("✅ Schema ready.")

def reset_graph(batch=10000):
    """Xoá toàn bộ graph theo batch (AuraDB free tier không chịu được DETACH DELETE một lần)."""
    total = 0
    while True:
        n = run_cypher(
            "MATCH (n) WITH n LIMIT $b DETACH DELETE n RETURN count(n) AS n",
            b=int(batch),
        )[0]["n"]
        total += n
        if n == 0:
            break
    print(f"Đã xoá {total:,} node.")

RESET_GRAPH_BEFORE_INGEST = True

connect_neo4j()
setup_graph_schema()
if RESET_GRAPH_BEFORE_INGEST:
    reset_graph()

✅ Neo4j connected (database = 5a93f3f3).

✅ Schema ready.
Đã xoá 0 node.

In [7]:
#@title 1.5 — Loader + exact dedup + chunking
def norm_space(x):
    return re.sub(r"\s+", " ", str(x or "")).strip()

def sha1(x):
    return hashlib.sha1(str(x).encode("utf-8", errors="ignore")).hexdigest()

def pick_col(df, candidates, required=True):
    lookup = {str(c).lower(): c for c in df.columns}
    for c in candidates:
        if c.lower() in lookup:
            return lookup[c.lower()]
    if required:
        raise KeyError(f"Missing one of columns: {candidates}")
    return None

def load_news(path):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(path)
    if path.suffix.lower() == ".csv":
        return pd.read_csv(path)
    if path.suffix.lower() in {".jsonl", ".ndjson"}:
        return pd.read_json(path, lines=True)
    if path.suffix.lower() == ".json":
        return pd.read_json(path)
    if path.suffix.lower() in {".parquet", ".pq"}:
        return pd.read_parquet(path)
    raise ValueError(f"Unsupported: {path.suffix}")

def standardize_news(raw):
    # Schema của data dump không cố định -> dò cột theo allowlist, nếu trượt thì fallback heuristic.
    text_col = pick_col(
        raw,
        ["text", "content", "article", "body", "story", "story_text",
         "post_text", "markdown", "description", "full_text"],
        required=False,
    )
    if text_col is None:
        obj_cols = [c for c in raw.columns if raw[c].dtype == object]
        if not obj_cols:
            raise KeyError(f"Không tìm thấy cột văn bản trong: {list(raw.columns)}")
        text_col = max(obj_cols, key=lambda c: raw[c].astype(str).str.len().head(1000).mean())
        print(f"[loader] Fallback: chọn cột text = '{text_col}'")

    title_col = pick_col(raw, ["title", "headline", "story_title", "name"], required=False)
    date_col = pick_col(
        raw,
        ["published_date", "date", "published_at", "created_at", "created_time", "time", "timestamp"],
        required=False,
    )
    id_col = pick_col(raw, ["id", "article_id", "story_id", "uuid", "objectID", "post_id"], required=False)
    print(f"[loader] text={text_col} | title={title_col} | date={date_col} | id={id_col}")

    df = pd.DataFrame()
    df["text"] = raw[text_col].fillna("").map(norm_space)
    df["title"] = raw[title_col].fillna("").map(norm_space) if title_col else ""

    if date_col:
        df["published_date"] = (
            pd.to_datetime(raw[date_col], errors="coerce", utc=True)
            .dt.strftime("%Y-%m-%d")
            .fillna("")
        )
    else:
        df["published_date"] = ""

    if id_col:
        df["article_id"] = raw[id_col].astype(str)
    else:
        df["article_id"] = [
            sha1(f"{t}\n{x}")[:20] for t, x in zip(df["title"], df["text"])
        ]

    if PREPEND_TITLE_TO_TEXT and title_col:
        # Headline mang phần lớn thực thể trong tin công nghệ -> đưa vào cùng trường text.
        df["text"] = [
            norm_space(f"{t}. {x}") if t and not x.lower().startswith(t.lower()[:40]) else norm_space(x or t)
            for t, x in zip(df["title"], df["text"])
        ]

    df = df[df["text"].str.len() >= 80].copy()
    df["dedup_key"] = [
        sha1(norm_space(f"{t}\n{x}").lower())
        for t, x in zip(df["title"], df["text"])
    ]
    before = len(df)
    df = df.drop_duplicates("dedup_key").drop(columns="dedup_key").reset_index(drop=True)
    print(f"Exact dedup: {before:,} -> {len(df):,}")

    if LAB_MAX_ARTICLES and len(df) > LAB_MAX_ARTICLES:
        df = df.sample(LAB_MAX_ARTICLES, random_state=SEED).sort_index().reset_index(drop=True)
    return df

def chunk_text(text, size=220, overlap=40):
    words = norm_space(text).split()
    step = max(1, size - overlap)
    out = []
    for start in range(0, len(words), step):
        part = words[start:start+size]
        if not part:
            break
        out.append(" ".join(part))
        if start + size >= len(words):
            break
    return out

def build_chunks(news_df):
    rows = []
    for r in tqdm(news_df.itertuples(index=False), total=len(news_df), desc="Chunking"):
        for i, text in enumerate(chunk_text(r.text, CHUNK_WORDS, CHUNK_OVERLAP_WORDS)):
            rows.append({
                "chunk_id": f"{r.article_id}::c{i:04d}",
                "article_id": r.article_id,
                "title": r.title,
                "published_date": r.published_date,
                "text": text,
            })
            if LAB_MAX_CHUNKS and len(rows) >= LAB_MAX_CHUNKS:
                return pd.DataFrame(rows)
    return pd.DataFrame(rows)

# raw_df = load_news(DATA_PATH)
# news_df = standardize_news(raw_df)
# chunks_df = build_chunks(news_df)
# display(chunks_df.head())

raw_df = load_news(DATA_PATH)
print("Raw shape:", raw_df.shape)
print("Columns:", list(raw_df.columns))

news_df = standardize_news(raw_df)
print(f"Bài viết sau exact dedup + scale guard: {len(news_df):,}")
RUN_STATE["ingest"] = {
    "raw_rows": int(raw_df.shape[0]),
    "articles_after_exact_dedup": int(len(news_df)),
}
display(news_df.head(3)[["article_id", "published_date", "title"]])

Raw shape: (5000, 7)
Columns: ['companyName', 'companyUrl', 'published_at', 'url', 'title', 'main_image', 'description']
[loader] text=description | title=title | date=published_at | id=None

Exact dedup: 2,694 -> 2,118
Bài viết sau exact dedup + scale guard: 2,118

,article_id,published_date,title
0,1a05beb7aa3071be6fd7,2023-05-16,onsemi and Sineng Electric Spearhead the Development of Sustainable Energy Applications
1,ec98609611765e97440d,2023-05-02,Adobe student receives national Information and Technology award
2,8e922bc62b578e73e815,2023-05-01,Modernizing State Services: Harnessing Technology for Enhanced Public Service Delivery

### 🎯 AI Coding Agent Challenge A — Near Dedup
Exact hash không bắt được bài repost/near-duplicate.

Hãy dùng AI Agent thiết kế thêm **MinHash/LSH, SimHash hoặc embedding+ANN**.  
**Không chấp nhận** pairwise cosine `O(N²)` trên toàn dataset.

Trong báo cáo nêu:
1. threshold,
2. false positive,
3. cách audit cặp bị merge.

In [8]:
#@title 1.5b — Challenge A: Near-dedup bằng MinHash + LSH (không O(N²))
# Ý tưởng: shingle 5-gram -> MinHash 128 perm -> banded LSH sinh candidate ->
# chỉ tính Jaccard thật trên candidate. Chi phí O(N * perm + #candidate),
# không bao giờ so sánh pairwise toàn bộ dataset.

SHINGLE_K = 5              # số từ mỗi shingle
MINHASH_PERM = 128         # số hàm băm
LSH_BANDS = 32             # 32 band x 4 row -> ngưỡng lọt candidate ~ (1/32)^(1/4) = 0.42
NEAR_DEDUP_THRESHOLD = 0.80  # Jaccard thật tối thiểu để coi là near-duplicate

# True  -> loại luôn bản trùng lặp gần khỏi corpus.
# False -> chỉ tính audit và báo cáo, KHÔNG xoá dòng nào.
#          Dùng False khi Golden Dataset được xây trên đúng chỉ số dòng của file gốc,
#          hoặc khi câu hỏi cross-doc cần chính các bài repost làm bằng chứng.
NEAR_DEDUP_APPLY = str(get_secret("NEAR_DEDUP_APPLY", "1")).lower() not in ("0", "false", "no")

_rng = np.random.RandomState(SEED)
_MH_A = _rng.randint(1, 2**63 - 1, size=MINHASH_PERM, dtype=np.int64).astype(np.uint64) | np.uint64(1)
_MH_B = _rng.randint(0, 2**63 - 1, size=MINHASH_PERM, dtype=np.int64).astype(np.uint64)
_MAXH = np.uint64(0xFFFFFFFFFFFFFFFF)

def dedup_norm(text):
    s = unicodedata.normalize("NFKC", str(text or "")).lower()
    s = re.sub(r"[^a-z0-9\s]", " ", s)
    return re.sub(r"\s+", " ", s).strip()

def shingle_set(text, k=SHINGLE_K):
    words = dedup_norm(text).split()
    if len(words) < k:
        return {" ".join(words)} if words else set()
    return {" ".join(words[i:i + k]) for i in range(len(words) - k + 1)}

def _shingle_hashes(shingles):
    return np.array(
        [int.from_bytes(hashlib.blake2b(s.encode("utf-8"), digest_size=8).digest(), "big")
         for s in shingles],
        dtype=np.uint64,
    )

def minhash_signature(shingles):
    """Multiply-shift hashing trên uint64 (tràn số = mod 2^64, vẫn là song ánh)."""
    if not shingles:
        return np.full(MINHASH_PERM, _MAXH, dtype=np.uint64)
    h = _shingle_hashes(shingles)
    with np.errstate(over="ignore"):
        perm = (h[:, None] * _MH_A[None, :]) + _MH_B[None, :]
    return perm.min(axis=0)

def build_signatures(texts, desc="MinHash"):
    sets, sigs = [], []
    for t in tqdm(texts, desc=desc):
        sh = shingle_set(t)
        sets.append(sh)
        sigs.append(minhash_signature(sh))
    return sets, np.vstack(sigs)

def lsh_candidate_pairs(sigs, bands=LSH_BANDS):
    rows = sigs.shape[1] // bands
    pairs = set()
    for b in range(bands):
        block = sigs[:, b * rows:(b + 1) * rows]
        buckets = defaultdict(list)
        for i in range(block.shape[0]):
            buckets[hashlib.blake2b(block[i].tobytes(), digest_size=8).digest()].append(i)
        for members in buckets.values():
            if len(members) < 2 or len(members) > 200:   # bỏ bucket khổng lồ -> tránh bùng nổ
                continue
            for x in range(len(members)):
                for y in range(x + 1, len(members)):
                    pairs.add((members[x], members[y]))
    return sorted(pairs)

def jaccard(a, b):
    if not a or not b:
        return 0.0
    inter = len(a & b)
    return inter / float(len(a) + len(b) - inter)

def near_dedup(df, threshold=NEAR_DEDUP_THRESHOLD):
    """Trả về (df_đã_lọc, audit_df). Giữ bản dài nhất / cũ nhất trong mỗi cụm."""
    texts = (df["title"].fillna("") + ". " + df["text"].fillna("")).tolist()
    sets, sigs = build_signatures(texts)
    cands = lsh_candidate_pairs(sigs)

    uf = UnionFindSimple(len(df))
    audit = []
    for i, j in cands:
        est = float((sigs[i] == sigs[j]).mean())
        real = jaccard(sets[i], sets[j])
        keep = real >= threshold
        audit.append({
            "left_article_id": df.article_id.iloc[i],
            "right_article_id": df.article_id.iloc[j],
            "left_title": df.title.iloc[i][:120],
            "right_title": df.title.iloc[j][:120],
            "minhash_est": round(est, 3),
            "jaccard_true": round(real, 3),
            "decision": "MERGE_NEAR_DUP" if keep else "REJECT_BELOW_THRESHOLD",
        })
        if keep:
            uf.union(i, j)

    groups = defaultdict(list)
    for i in range(len(df)):
        groups[uf.find(i)].append(i)

    keep_idx = []
    for members in groups.values():
        # Đại diện = bài dài nhất; hoà nhau thì lấy ngày xuất bản sớm nhất.
        best = sorted(members, key=lambda i: (-len(str(df.text.iloc[i])), str(df.published_date.iloc[i])))[0]
        keep_idx.append(best)

    out = df.iloc[sorted(keep_idx)].reset_index(drop=True)
    return out, pd.DataFrame(audit)

class UnionFindSimple:
    def __init__(self, n):
        self.p = list(range(n))
    def find(self, x):
        while self.p[x] != x:
            self.p[x] = self.p[self.p[x]]
            x = self.p[x]
        return x
    def union(self, a, b):
        a, b = self.find(a), self.find(b)
        if a != b:
            self.p[b] = a

before_near = len(news_df)
_deduped_df, near_dup_audit_df = near_dedup(news_df)
if NEAR_DEDUP_APPLY:
    news_df = _deduped_df
    removed = before_near - len(news_df)
    print(f"Near-dedup: {before_near:,} -> {len(news_df):,} (bỏ {removed:,} bài)")
else:
    removed = before_near - len(_deduped_df)
    print(f"Near-dedup (CHỈ BÁO CÁO, không xoá): phát hiện {removed:,} bài trùng lặp gần "
          f"trên tổng {before_near:,}")
print(f"Candidate pair từ LSH: {len(near_dup_audit_df):,} "
      f"| merge: {(near_dup_audit_df.decision == 'MERGE_NEAR_DUP').sum() if len(near_dup_audit_df) else 0}")

if len(near_dup_audit_df):
    near_dup_audit_df.sort_values("jaccard_true", ascending=False).to_csv(
        OUTPUT_DIR / "near_dedup_audit.csv", index=False
    )
    display(near_dup_audit_df.sort_values("jaccard_true", ascending=False).head(10))

RUN_STATE["near_dedup"] = {
    "applied": bool(NEAR_DEDUP_APPLY),
    "duplicates_detected": int(removed),
    "threshold": NEAR_DEDUP_THRESHOLD,
    "perm": MINHASH_PERM, "bands": LSH_BANDS, "shingle_k": SHINGLE_K,
    "candidate_pairs": int(len(near_dup_audit_df)),
    "merged_pairs": int((near_dup_audit_df.decision == "MERGE_NEAR_DUP").sum()) if len(near_dup_audit_df) else 0,
    "articles_before": int(before_near),
    "articles_after": int(len(news_df)),
}

# Chunking chạy SAU near-dedup để không index lại nội dung trùng lặp.
chunks_df = build_chunks(news_df)
print(f"Chunks: {len(chunks_df):,}")
RUN_STATE["chunks"] = {"n_chunks": int(len(chunks_df))}
display(chunks_df.head(3))

MinHash:   0%|          | 0/2118 [00:00<?, ?it/s]

MinHash:  58%|█████▊    | 1239/2118 [00:00<00:00, 12113.17it/s]

MinHash: 100%|██████████| 2118/2118 [00:00<00:00, 11012.70it/s]

Near-dedup (CHỈ BÁO CÁO, không xoá): phát hiện 12 bài trùng lặp gần trên tổng 2,118
Candidate pair từ LSH: 504 | merge: 12

,left_article_id,right_article_id,left_title,right_title,minhash_est,jaccard_true,decision
177,26c22c308fb6716a3eda,cc60dc5511e323ac4d0a,Tech Media & Telecom Roundup: Market Talk,Tech Media & Telecom Roundup: Market Talk,1.000,1.000,MERGE_NEAR_DUP
98,d2f10b6eb420a221b002,e41e603c9b2b467c7a45,CereCore® expands healthcare technology services into the UK,CereCore expands healthcare technology services into the UK,1.000,1.000,MERGE_NEAR_DUP
336,919a7d918c23097ae974,9cec56f34793ad5c585e,411 is going out of service for millions of Americans,411 is going out of service for millions of Americans,1.000,1.000,MERGE_NEAR_DUP
71,42f24c797073748f73f8,e5ccd70f01654458127e,Sensormatic Solutions by Johnson Controls shares 2022 U.S. Super Saturday shopper traffic insights,Sensormatic Solutions by Johnson Controls shares 2022 U.S. Super Saturday shopper traffic insights,0.992,0.979,MERGE_NEAR_DUP
26,8c5930949a3d9f3c3a38,8e58296629f84469cd8d,Samsung Showcases Groundbreaking Logic Innovations at System LSI Tech Day 2023,Samsung Showcases Groundbreaking Logic Innovations at System LSI Tech Day 2023,0.875,0.878,MERGE_NEAR_DUP
478,c86b8357f117fa7f9444,c967562f9d4628db990c,Stock market today: Wall Street is mixed; Big Tech climbs,Stock market today: Wall Street is mixed; Big Tech climbs,0.883,0.878,MERGE_NEAR_DUP
501,99e4dff966ca14987a42,e1dd933ce175e571f1fc,Knicks rally to beat Pacers 109-106 for 7th straight victory,Knicks rally to beat Pacers 109-106 for 7th straight victory,0.836,0.848,MERGE_NEAR_DUP
393,e6090305820383267481,20900bb77008b0464c81,411 phone number is going out of service for millions of Americans,411 is going out of service for millions of Americans,0.828,0.839,MERGE_NEAR_DUP
130,05a134c06ab008a9d52c,f88a9282762685bb8f9b,Fidelity National Information Services (FIS) Stock Moves -0.9%: What You Should Know,Fidelity National Information Services (FIS) Stock Moves -0.9%: What You Should Know,0.828,0.836,MERGE_NEAR_DUP
96,201da7854b95e5ee4a3a,275fc1333cf98e260eec,L T Technology Services and Qualcomm Selected by Thales for Enabling 5G Private Networks in Urban Railways,L&T Technology Services and Qualcomm Selected by Thales for Enabling 5G Private Networks in Urban Railways,0.812,0.814,MERGE_NEAR_DUP

Chunking:   0%|          | 0/2118 [00:00<?, ?it/s]

Chunking: 100%|██████████| 2118/2118 [00:00<00:00, 79394.55it/s]

Chunks: 2,118

,chunk_id,article_id,title,published_date,text
0,1a05beb7aa3071be6fd7::c0000,1a05beb7aa3071be6fd7,onsemi and Sineng Electric Spearhead the Development of Sustainable Energy Applications,2023-05-16,onsemi and Sineng Electric Spearhead the Development of Sustainable Energy Applications. (Nasdaq: ON) a leader in in...
1,ec98609611765e97440d::c0000,ec98609611765e97440d,Adobe student receives national Information and Technology award,2023-05-02,Adobe student receives national Information and Technology award. ELKO — An eighth grader at Adobe Middle School is ...
2,8e922bc62b578e73e815::c0000,8e922bc62b578e73e815,Modernizing State Services: Harnessing Technology for Enhanced Public Service Delivery,2023-05-01,Modernizing State Services: Harnessing Technology for Enhanced Public Service Delivery. To deliver 21st-century gove...

In [9]:
#@title 1.6 — LLM wrapper có retry + JSON parsing
from groq import Groq
groq_client = Groq(api_key=GROQ_API_KEY) if GROQ_API_KEY else None

def parse_json_object(text):
    text = str(text).strip()
    text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.I)
    text = re.sub(r"\s*```$", "", text)
    a, b = text.find("{"), text.rfind("}")
    if a < 0 or b <= a:
        raise ValueError("No JSON object found.")
    return json.loads(text[a:b+1])

def groq_chat(messages, model=None, json_mode=False, max_retries=4):
    if groq_client is None:
        raise RuntimeError("Thiếu GROQ_API_KEY.")
    model = model or GROQ_MODEL
    if not model:
        raise RuntimeError("Thiếu GROQ_MODEL.")

    last = None
    for attempt in range(max_retries):
        try:
            kwargs = {
                "model": model,
                "messages": messages,
                "temperature": 0.0,
            }
            if json_mode:
                kwargs["response_format"] = {"type": "json_object"}

            resp = groq_client.chat.completions.create(**kwargs)
            usage = {}
            if getattr(resp, "usage", None):
                usage = {
                    "prompt_tokens": getattr(resp.usage, "prompt_tokens", None),
                    "completion_tokens": getattr(resp.usage, "completion_tokens", None),
                    "total_tokens": getattr(resp.usage, "total_tokens", None),
                }
            return resp.choices[0].message.content, usage
        except Exception as e:
            last = e
            if attempt == max_retries - 1:
                break
            time.sleep(min(20, 2**attempt + random.random()))
    raise RuntimeError(last)

def groq_json(system, user, model=None):
    text, usage = groq_chat(
        [{"role": "system", "content": system},
         {"role": "user", "content": user}],
        model=model,
        json_mode=True,
    )
    return parse_json_object(text), usage

In [10]:
# === LOCAL RUN OVERRIDE: cache dia cho moi loi goi LLM (chong mat tien khi chay lai) ===
import sqlite3, hashlib, threading
_CACHE_DB = str(OUTPUT_DIR.parent / "llm_cache.sqlite")
_cache_lock = threading.Lock()
_cache_conn = sqlite3.connect(_CACHE_DB, check_same_thread=False)
_cache_conn.execute("CREATE TABLE IF NOT EXISTS c (k TEXT PRIMARY KEY, v TEXT)")
_cache_conn.commit()

def _ckey(*parts):
    return hashlib.sha256("||".join(map(str, parts)).encode("utf-8")).hexdigest()

def _cget(k):
    with _cache_lock:
        row = _cache_conn.execute("SELECT v FROM c WHERE k=?", (k,)).fetchone()
    return json.loads(row[0]) if row else None

def _cput(k, v):
    with _cache_lock:
        _cache_conn.execute("INSERT OR REPLACE INTO c VALUES (?,?)", (k, json.dumps(v)))
        _cache_conn.commit()

# Groq free tier: 8000 tokens/phut. Chu dong dieu tiet de khong dinh 429 lien tuc.
GROQ_TPM_BUDGET = 7000
_TOKEN_LOG = []

def _pace():
    while True:
        now = time.time()
        while _TOKEN_LOG and now - _TOKEN_LOG[0][0] > 60:
            _TOKEN_LOG.pop(0)
        used = sum(t for _, t in _TOKEN_LOG)
        if used < GROQ_TPM_BUDGET:
            return
        time.sleep(min(5.0, 61 - (now - _TOKEN_LOG[0][0])))

_raw_groq_chat = groq_chat

# gpt-oss ho tro reasoning_effort. Cac tac vu co hoc (coref, trich seed, kiem tra
# du ngu canh) dung "low" de giam completion tokens ~50% ma khong doi ket qua;
# trich xuat KG va sinh cau tra loi giu muc mac dinh.
_LOW_EFFORT_MARKERS = ("coreference-resolution component", "seed entities for graph retrieval",
                       "whether the supplied retrieval context is sufficient")

def _effort_for(messages):
    sys_txt = " ".join(m.get("content", "") for m in messages if m.get("role") == "system")
    return "low" if any(k in sys_txt for k in _LOW_EFFORT_MARKERS) else None

def groq_chat(messages, model=None, json_mode=False, max_retries=6):
    model = model or GROQ_MODEL
    effort = _effort_for(messages)
    key = _ckey("groq", model, json_mode, effort, json.dumps(messages, ensure_ascii=False))
    hit = _cget(key)
    if hit is not None:
        return hit[0], hit[1]

    _pace()
    last = None
    for attempt in range(max_retries):
        try:
            kwargs = {"model": model, "messages": messages, "temperature": 0.0}
            if json_mode:
                kwargs["response_format"] = {"type": "json_object"}
            if effort:
                kwargs["reasoning_effort"] = effort
            resp = groq_client.chat.completions.create(**kwargs)
            usage = {}
            if getattr(resp, "usage", None):
                usage = {"prompt_tokens": resp.usage.prompt_tokens,
                         "completion_tokens": resp.usage.completion_tokens,
                         "total_tokens": resp.usage.total_tokens}
            text = resp.choices[0].message.content
            _TOKEN_LOG.append((time.time(), usage.get("total_tokens") or 0))
            _cput(key, [text, usage])
            return text, usage
        except Exception as e:
            last = e
            if attempt == max_retries - 1:
                break
            time.sleep(min(30, 2 ** attempt + random.random()))
    raise RuntimeError(last)

CACHE_STATS = {"hits": 0, "miss": 0}
print("LLM cache:", _CACHE_DB)

LLM cache: d:\VinUni-AI20K\K4-Track3-Lab19-2A202601941-NguyenHoangVu\llm_cache.sqlite

## 1.7 — Coreference Resolution

Yêu cầu:
- chỉ resolve đại từ khi antecedent rõ trong cùng chunk,
- không invent fact,
- giữ nguyên số/ngày/ticker/product,
- ambiguity → giữ nguyên và log `unresolved_mentions`.

**Failure mode quan trọng:** false coreference → false edge.

In [ ]:
#@title 1.7 — Coreference resolution theo batch
COREF_SYSTEM = """
You are a conservative coreference-resolution component for a knowledge-graph pipeline.
Resolve pronouns and generic references only when the antecedent is clearly supported in the same chunk.
Never invent facts. Preserve dates, numbers, tickers and product names.
Return strict JSON only.
""".strip()

def resolve_coref_batch(batch_df):
    payload = [{"chunk_id": r.chunk_id, "text": r.text}
               for r in batch_df.itertuples(index=False)]

    prompt = f"""
Resolve coreferences.

Return:
{{
  "items": [
    {{
      "chunk_id": "...",
      "resolved_text": "...",
      "unresolved_mentions": ["..."]
    }}
  ]
}}

INPUT:
{json.dumps(payload, ensure_ascii=False)}
""".strip()

    obj, usage = groq_json(COREF_SYSTEM, prompt)
    by_id = {x.get("chunk_id"): x for x in obj.get("items", [])}

    rows = []
    for r in batch_df.itertuples(index=False):
        item = by_id.get(r.chunk_id, {})
        rows.append({
            "chunk_id": r.chunk_id,
            "resolved_text": norm_space(item.get("resolved_text") or r.text),
            "unresolved_mentions": item.get("unresolved_mentions", []),
        })
    return pd.DataFrame(rows), usage

# Chỉ những chunk thực sự có đại từ/tham chiếu chung mới cần LLM phân giải.
# Với tin ngắn, phần lớn chunk không có đại từ nào -> gọi LLM cho chúng là đốt quota vô ích.
COREF_ONLY_IF_PRONOUN = True
PRONOUN_RE = re.compile(
    r"\b(it|its|it's|they|their|them|he|his|him|she|her|hers|"
    r"the company|the companies|the startup|the firm|the group|the team|"
    r"the bank|the maker|the agency|this company)\b", re.I)

def needs_coref(text):
    return bool(PRONOUN_RE.search(str(text or "")))

def run_coref(chunks_subset, batch_size=5):
    out = []

    if COREF_ONLY_IF_PRONOUN:
        mask = chunks_subset.text.map(needs_coref)
        todo = chunks_subset[mask]
        skipped = chunks_subset[~mask]
        print(f"Coref: {len(todo):,}/{len(chunks_subset):,} chunk có đại từ cần phân giải "
              f"({len(skipped):,} chunk bỏ qua).")
        if len(skipped):
            out.append(pd.DataFrame({
                "chunk_id": skipped.chunk_id.tolist(),
                "resolved_text": skipped.text.tolist(),
                "unresolved_mentions": [[] for _ in range(len(skipped))],
            }))
    else:
        todo = chunks_subset

    chunks_subset = todo
    for start in tqdm(range(0, len(chunks_subset), batch_size), desc="Coref"):
        batch = chunks_subset.iloc[start:start+batch_size]
        try:
            df, _ = resolve_coref_batch(batch)
        except Exception:
            df = pd.DataFrame({
                "chunk_id": batch["chunk_id"].tolist(),
                "resolved_text": batch["text"].tolist(),
                "unresolved_mentions": [["COREF_BATCH_FAILED"] for _ in range(len(batch))],
            })
        out.append(df)
    return pd.concat(out, ignore_index=True)

ENTITY_TOKEN_RE = re.compile(r"\b[A-Z][A-Za-z0-9&.\-]+(?:\s+[A-Z][A-Za-z0-9&.\-]+)*")

def entity_density(text):
    """Đếm cụm viết hoa (proxy NER rẻ tiền) để ưu tiên chunk đáng gửi qua LLM."""
    t = str(text or "")
    cands = [m for m in ENTITY_TOKEN_RE.findall(t) if len(m) > 2]
    return len(set(cands))

def select_extraction_chunks(df, max_chunks=None, per_article=2):
    """Chọn chunk để trích xuất KG.

    EXTRACTION_MAX_CHUNKS = None -> lấy toàn bộ.
    Ngược lại: ưu tiên chunk giàu thực thể, nhưng giới hạn số chunk mỗi bài để
    độ phủ trải đều toàn corpus thay vì dồn hết vào vài bài đầu tiên.
    """
    if not max_chunks or max_chunks >= len(df):
        return df.copy()

    scored = df.copy()
    scored["_density"] = scored.text.map(entity_density)
    scored["_rank_in_article"] = (
        scored.sort_values("_density", ascending=False).groupby("article_id").cumcount()
    )
    picked = (scored[scored._rank_in_article < per_article]
              .sort_values("_density", ascending=False)
              .head(max_chunks))
    if len(picked) < max_chunks:   # còn quota thì lấy thêm chunk đứng sau
        rest = scored.drop(picked.index).sort_values("_density", ascending=False)
        picked = pd.concat([picked, rest.head(max_chunks - len(picked))])
    out = picked.sort_index().drop(columns=["_density", "_rank_in_article"])
    print(f"Chọn {len(out):,}/{len(df):,} chunk để trích xuất "
          f"(ưu tiên mật độ thực thể, tối đa {per_article} chunk/bài).")
    return out.reset_index(drop=True)

extraction_source = select_extraction_chunks(chunks_df, EXTRACTION_MAX_CHUNKS)
coref_df = run_coref(extraction_source, batch_size=COREF_BATCH)
extraction_source = extraction_source.merge(coref_df, on="chunk_id", how="left")
extraction_source["resolved_text"] = extraction_source["resolved_text"].fillna(extraction_source["text"])

_n_unres = int(extraction_source.unresolved_mentions.map(
    lambda x: len(x) if isinstance(x, list) else 0).sum())
_n_failed = int(extraction_source.unresolved_mentions.map(
    lambda x: isinstance(x, list) and "COREF_BATCH_FAILED" in x).sum())
_n_changed = int((extraction_source.resolved_text.fillna("") != extraction_source.text).sum())

print(f"Chunk đưa vào extraction: {len(extraction_source):,}")
print(f"Chunk bị đổi text sau coref: {_n_changed:,}")
print(f"Tổng unresolved_mentions: {_n_unres:,} | batch lỗi: {_n_failed:,}")

RUN_STATE["coref"] = {
    "chunks": int(len(extraction_source)),
    "changed_chunks": _n_changed,
    "unresolved_mentions": _n_unres,
    "failed_batches_chunks": _n_failed,
}

# Spot-check thủ công: xem 3 chunk bị sửa nhiều nhất để bắt false coreference.
_spot = extraction_source.copy()
_spot["delta"] = (_spot.resolved_text.str.len() - _spot.text.str.len()).abs()
display(_spot.sort_values("delta", ascending=False)
        .head(3)[["chunk_id", "text", "resolved_text", "unresolved_mentions"]])
extraction_source[["chunk_id", "text", "resolved_text", "unresolved_mentions"]].to_csv(
    OUTPUT_DIR / "coref_spotcheck.csv", index=False)

# PHẦN 2 — TRIPLE EXTRACTION & NEO4J BULK INSERT (15–45')

## Graph schema
**Nodes:** `Company`, `Person`, `Technology` + base label `Entity`.

**Relations:** `ACQUIRED`, `DEVELOPED`, `INVESTED_IN`, `FOUNDED`, `WORKED_AT`, `PARTNERED_WITH`, `USES`, `LEADS`.

**Mỗi edge bắt buộc:** `source_chunk_id`, `published_date`; khuyến nghị thêm `evidence`, `confidence`.

> Relation type phải qua allowlist trước khi ghép vào Cypher.

In [ ]:
#@title 2.1 — NER + RE extraction
ALLOWED_NODE_TYPES = {"Company", "Person", "Technology"}
ALLOWED_RELATIONS = {
    "ACQUIRED", "DEVELOPED", "INVESTED_IN", "FOUNDED",
    "WORKED_AT", "PARTNERED_WITH", "USES", "LEADS"
}

EXTRACT_SYSTEM = f"""
Extract a high-precision knowledge graph from tech-news text.
Allowed node types: {sorted(ALLOWED_NODE_TYPES)}
Allowed relations: {sorted(ALLOWED_RELATIONS)}
Use only explicitly supported facts. Prefer precision over recall.
Every relation needs short evidence. Return strict JSON only.
""".strip()

def extract_batch(batch_df):
    payload = [{
        "chunk_id": r.chunk_id,
        "published_date": r.published_date,
        "text": getattr(r, "resolved_text", None) or r.text,
    } for r in batch_df.itertuples(index=False)]

    prompt = f"""
Return:
{{
  "items": [
    {{
      "chunk_id": "...",
      "relations": [
        {{
          "source": "...",
          "source_type": "Company|Person|Technology",
          "relation": "ALLOWED_RELATION",
          "target": "...",
          "target_type": "Company|Person|Technology",
          "evidence": "...",
          "confidence": 0.0
        }}
      ]
    }}
  ]
}}

INPUT:
{json.dumps(payload, ensure_ascii=False)}
""".strip()
    return groq_json(EXTRACT_SYSTEM, prompt)

def run_extraction(source_df, batch_size=4):
    meta = source_df.set_index("chunk_id")["published_date"].to_dict()
    triples, errors = [], []

    for start in tqdm(range(0, len(source_df), batch_size), desc="NER+RE"):
        batch = source_df.iloc[start:start+batch_size]
        try:
            obj, _ = extract_batch(batch)
        except Exception as e:
            errors.append({"start": start, "error": str(e)})
            continue

        for item in obj.get("items", []):
            cid = item.get("chunk_id")
            if cid not in meta:
                continue
            for x in item.get("relations", []):
                s, t = norm_space(x.get("source")), norm_space(x.get("target"))
                st, tt, rel = x.get("source_type"), x.get("target_type"), x.get("relation")
                if not s or not t:
                    continue
                if st not in ALLOWED_NODE_TYPES or tt not in ALLOWED_NODE_TYPES:
                    continue
                if rel not in ALLOWED_RELATIONS:
                    continue
                triples.append({
                    "source_raw": s,
                    "source_type": st,
                    "relation": rel,
                    "target_raw": t,
                    "target_type": tt,
                    "source_chunk_id": cid,
                    "published_date": meta[cid] or "",
                    "evidence": norm_space(x.get("evidence")),
                    "confidence": float(x.get("confidence") or 0.0),
                })

    return pd.DataFrame(triples), pd.DataFrame(errors)

raw_triples_df, extraction_errors_df = run_extraction(extraction_source, batch_size=EXTRACT_BATCH)

if raw_triples_df.empty:
    raise RuntimeError(
        "Không trích xuất được triple nào. Kiểm tra GROQ_MODEL / rate limit / nội dung chunk."
    )

print(f"Triple thô: {len(raw_triples_df):,} | batch lỗi: {len(extraction_errors_df):,}")
print("Phân bố relation:")
display(raw_triples_df.relation.value_counts().to_frame("count"))
print("Confidence trung bình:", round(float(raw_triples_df.confidence.mean()), 3))
print("Tỷ lệ triple có evidence:",
      round(float((raw_triples_df.evidence.fillna("").str.len() > 0).mean()), 3))

RUN_STATE["extraction"] = {
    "raw_triples": int(len(raw_triples_df)),
    "failed_batches": int(len(extraction_errors_df)),
    "relation_counts": raw_triples_df.relation.value_counts().to_dict(),
    "mean_confidence": round(float(raw_triples_df.confidence.mean()), 3),
    "evidence_coverage": round(float((raw_triples_df.evidence.fillna("").str.len() > 0).mean()), 3),
}
raw_triples_df.to_csv(OUTPUT_DIR / "raw_triples.csv", index=False)
display(raw_triples_df.head())

## 2.2 — Entity Resolution bằng Vector Similarity

Pipeline:
1. Manual aliases cho ticker/tên rất phổ biến.
2. Embedding ANN candidate.
3. Lexical guard để giảm false merge.
4. Xuất audit table.

### 🎯 AI Coding Agent Challenge B
Cải tiến guard cho:
- ticker,
- suffix `Inc./Corp./Ltd.`,
- product chứa company name,
- người trùng họ/tên gần giống.

In [ ]:
#@title 2.2 — Entity resolution
CORP_SUFFIXES = {"inc","incorporated","corp","corporation","ltd","limited","llc","plc","co","company"}
MANUAL_ALIASES = {
    "msft": "Microsoft",
    "microsoft corp": "Microsoft",
    "microsoft corporation": "Microsoft",
    "goog": "Google",
    "googl": "Google",
    "google llc": "Google",
    "meta platforms": "Meta",
    "meta platforms inc": "Meta",
    "aapl": "Apple",
    "apple inc": "Apple",
}

def norm_entity(name):
    s = unicodedata.normalize("NFKC", norm_space(name)).lower()
    s = re.sub(r"[^\w\s\-\.]", " ", s)
    return re.sub(r"\s+", " ", s).strip()

def strip_suffix(name):
    toks = norm_entity(name).replace(".", "").split()
    while toks and toks[-1] in CORP_SUFFIXES:
        toks.pop()
    return " ".join(toks)

# --- Challenge B: lexical guard nâng cấp (ticker / suffix / product / người trùng họ) ---
GENERIC_ORG_TOKENS = {
    "holdings", "holding", "group", "technologies", "technology", "labs", "lab",
    "systems", "solutions", "international", "worldwide", "platforms", "platform",
    "ventures", "partners", "ai",
}
GIVEN_NAME_RATIO = 0.90     # tên riêng phải gần như trùng khớp mới cho merge
COMPANY_RATIO = 0.72
TECH_RATIO = 0.84

def _tokens(name):
    return strip_suffix(name).split()

def _digits(name):
    return re.findall(r"\d+", norm_entity(name))

def _looks_like_ticker(raw_name):
    s = norm_space(raw_name)
    return bool(re.fullmatch(r"[A-Z]{2,5}", s))

def merge_guard(a, b, typ=None):
    """Trả về (allow, reason). Reason được ghi vào audit table để giải trình."""
    na, nb_ = strip_suffix(a), strip_suffix(b)
    ta, tb = _tokens(a), _tokens(b)

    if not na or not nb_:
        return False, "empty_after_normalization"

    # 1) Trùng khớp sau khi bỏ hậu tố pháp nhân (Inc./Corp./Ltd...) -> merge an toàn.
    if na == nb_:
        return True, "same_core_name_after_suffix_strip"

    # 2) Ticker (MSFT, AAPL...) chỉ merge qua MANUAL_ALIASES, không dựa vào vector.
    if _looks_like_ticker(a) or _looks_like_ticker(b):
        if norm_entity(a) in MANUAL_ALIASES or norm_entity(b) in MANUAL_ALIASES:
            return True, "ticker_manual_alias"
        return False, "ticker_needs_manual_alias"

    # 3) Khác số/phiên bản -> khác thực thể (GPT-4 vs GPT-3, Llama 2 vs Llama 3).
    if set(_digits(a)) != set(_digits(b)):
        return False, "version_or_digit_mismatch"

    # 4) Bao hàm token: "Apple Watch" vs "Apple", "Google Cloud" vs "Google".
    sa, sb = set(ta), set(tb)
    if sa and sb and (sa < sb or sb < sa):
        extra = (sb - sa) if sa < sb else (sa - sb)
        if typ == "Company" and extra <= GENERIC_ORG_TOKENS:
            return True, "company_generic_org_token"
        return False, f"extra_qualifier_tokens:{'/'.join(sorted(extra))}"

    # 5) Người: bắt buộc trùng họ, tên riêng phải khớp hoặc là chữ cái viết tắt.
    if typ == "Person":
        if not ta or not tb:
            return False, "person_missing_tokens"
        if ta[-1] != tb[-1]:
            return False, "different_surname"
        fa, fb = ta[0], tb[0]
        if fa == fb:
            return True, "same_full_name"
        if len(fa) == 1 or len(fb) == 1:      # "S. Altman" vs "Sam Altman"
            return (fa[0] == fb[0], "initial_match" if fa[0] == fb[0] else "initial_mismatch")
        if SequenceMatcher(None, fa, fb).ratio() >= GIVEN_NAME_RATIO:
            return True, "given_name_near_match"
        return False, "different_given_name"

    # 6) Fallback lexical ratio, chặt hơn với Technology vì tên sản phẩm rất gần nhau.
    ratio = SequenceMatcher(None, na, nb_).ratio()
    need = TECH_RATIO if typ == "Technology" else COMPANY_RATIO
    return (ratio >= need, f"lexical_ratio={ratio:.2f}(need>={need})")

EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
embedder = None

def get_embedder():
    global embedder
    if embedder is None:
        embedder = SentenceTransformer(EMBED_MODEL)
    return embedder

class UF:
    def __init__(self, n):
        self.p = list(range(n))
    def find(self, x):
        if self.p[x] != x:
            self.p[x] = self.find(self.p[x])
        return self.p[x]
    def union(self, a, b):
        a, b = self.find(a), self.find(b)
        if a != b:
            self.p[b] = a

def build_resolution_map(raw_triples_df, threshold=0.90, top_k=5):
    mentions = []
    for r in raw_triples_df.itertuples(index=False):
        mentions += [(r.source_type, r.source_raw), (r.target_type, r.target_raw)]

    counts = Counter((t, norm_entity(n)) for t, n in mentions)
    display_name = {}
    for t, n in mentions:
        display_name.setdefault((t, norm_entity(n)), n)

    mapping, audit = {}, []

    for key in counts:
        t, norm = key
        if norm in MANUAL_ALIASES:
            mapping[key] = MANUAL_ALIASES[norm]
            audit.append({
                "type": t, "left": display_name[key],
                "right": MANUAL_ALIASES[norm],
                "similarity": 1.0, "decision": "MERGE_MANUAL",
                "reason": "manual_alias_map",
            })

    for typ in sorted(ALLOWED_NODE_TYPES):
        keys = [k for k in counts if k[0] == typ and k not in mapping]
        if not keys:
            continue
        names = [display_name[k] for k in keys]
        vecs = get_embedder().encode(
            names, batch_size=128, show_progress_bar=False,
            normalize_embeddings=True
        ).astype("float32")

        index = faiss.IndexFlatIP(vecs.shape[1])
        index.add(vecs)
        sims, nbrs = index.search(vecs, min(top_k, len(names)))
        uf = UF(len(names))

        for i in range(len(names)):
            for score, j in zip(sims[i], nbrs[i]):
                if j < 0 or i >= j or float(score) < threshold:
                    continue
                ok, reason = merge_guard(names[i], names[j], typ)
                audit.append({
                    "type": typ, "left": names[i], "right": names[j],
                    "similarity": float(score),
                    "decision": "MERGE_VECTOR" if ok else "REJECT_GUARD",
                    "reason": reason,
                })
                if ok:
                    uf.union(i, j)

        groups = defaultdict(list)
        for i in range(len(names)):
            groups[uf.find(i)].append(i)

        for idxs in groups.values():
            best = sorted(
                idxs,
                key=lambda i: (-counts[keys[i]], len(names[i]), names[i].lower())
            )[0]
            canonical = names[best]
            for i in idxs:
                mapping[keys[i]] = canonical

    for key in counts:
        mapping.setdefault(key, display_name[key])

    return mapping, pd.DataFrame(audit)

def canonicalize_triples(raw_df, mapping):
    df = raw_df.copy()
    def canon(name, typ):
        n = norm_entity(name)
        return mapping.get((typ, n), MANUAL_ALIASES.get(n, name))

    df["source_name"] = [canon(n,t) for n,t in zip(df.source_raw, df.source_type)]
    df["target_name"] = [canon(n,t) for n,t in zip(df.target_raw, df.target_type)]
    df["source_name_norm"] = df.source_name.map(norm_entity)
    df["target_name_norm"] = df.target_name.map(norm_entity)
    df["source_id"] = [sha1(f"{t}:{n}")[:24] for t,n in zip(df.source_type, df.source_name_norm)]
    df["target_id"] = [sha1(f"{t}:{n}")[:24] for t,n in zip(df.target_type, df.target_name_norm)]
    return df[df.source_id != df.target_id].reset_index(drop=True)

ER_THRESHOLD = 0.90   # cosine similarity tối thiểu để sinh candidate merge
ER_TOP_K = 5

entity_map, entity_resolution_audit_df = build_resolution_map(
    raw_triples_df, threshold=ER_THRESHOLD, top_k=ER_TOP_K
)
triples_df = canonicalize_triples(raw_triples_df, entity_map)

_mentions_before = len(set(
    [(t, norm_entity(n)) for t, n in zip(raw_triples_df.source_type, raw_triples_df.source_raw)] +
    [(t, norm_entity(n)) for t, n in zip(raw_triples_df.target_type, raw_triples_df.target_raw)]
))
_entities_after = len(set(
    list(zip(triples_df.source_type, triples_df.source_name_norm)) +
    list(zip(triples_df.target_type, triples_df.target_name_norm))
))
print(f"Mention thực thể: {_mentions_before:,} -> canonical entity: {_entities_after:,}")
if len(entity_resolution_audit_df):
    print(entity_resolution_audit_df.decision.value_counts().to_dict())
    entity_resolution_audit_df.sort_values("similarity", ascending=False).to_csv(
        OUTPUT_DIR / "entity_resolution_audit.csv", index=False)

RUN_STATE["entity_resolution"] = {
    "threshold": ER_THRESHOLD, "top_k": ER_TOP_K,
    "mentions_before": int(_mentions_before),
    "entities_after": int(_entities_after),
    "audit_rows": int(len(entity_resolution_audit_df)),
    "decisions": entity_resolution_audit_df.decision.value_counts().to_dict()
                 if len(entity_resolution_audit_df) else {},
}
display(entity_resolution_audit_df.sort_values("similarity", ascending=False).head(20))

In [ ]:
#@title 2.3 — Node table + UNWIND bulk insert
def build_nodes(triples_df):
    rows = []
    for r in triples_df.itertuples(index=False):
        rows += [
            {"id":r.source_id,"name":r.source_name,"name_norm":r.source_name_norm,"type":r.source_type,"alias":r.source_raw},
            {"id":r.target_id,"name":r.target_name,"name_norm":r.target_name_norm,"type":r.target_type,"alias":r.target_raw},
        ]
    tmp = pd.DataFrame(rows)
    if tmp.empty:
        return tmp

    out = []
    for (node_id,name,name_norm,typ), g in tmp.groupby(["id","name","name_norm","type"]):
        aliases = sorted(set(g["alias"].map(norm_space)))
        out.append({
            "id":node_id, "name":name, "name_norm":name_norm, "type":typ,
            "aliases":aliases,
            "aliases_norm":sorted(set(norm_entity(x) for x in aliases))
        })
    return pd.DataFrame(out)

def batches(records, size=1000):
    for i in range(0, len(records), size):
        yield records[i:i+size]

def bulk_insert_nodes(nodes_df, batch_size=1000):
    for typ in sorted(ALLOWED_NODE_TYPES):
        part = nodes_df[nodes_df.type == typ]
        if part.empty:
            continue
        query = f"""
        UNWIND $rows AS row
        MERGE (n:Entity {{id: row.id}})
        SET n:{typ},
            n.name=row.name,
            n.name_norm=row.name_norm,
            n.entity_type=row.type,
            n.aliases=row.aliases,
            n.aliases_norm=row.aliases_norm
        """
        for b in batches(part.to_dict("records"), batch_size):
            run_cypher(query, rows=b)

def bulk_insert_edges(triples_df, batch_size=1000):
    required = {"source_chunk_id","published_date"}
    if not required.issubset(triples_df.columns):
        raise ValueError("Missing edge provenance.")

    for rel in sorted(ALLOWED_RELATIONS):
        part = triples_df[triples_df.relation == rel]
        if part.empty:
            continue

        query = f"""
        UNWIND $rows AS row
        MATCH (s:Entity {{id: row.source_id}})
        MATCH (t:Entity {{id: row.target_id}})
        MERGE (s)-[r:{rel} {{source_chunk_id: row.source_chunk_id}}]->(t)
        SET r.published_date=row.published_date,
            r.evidence=row.evidence,
            r.confidence=row.confidence
        """

        cols = ["source_id","target_id","source_chunk_id","published_date","evidence","confidence"]
        for b in batches(part[cols].to_dict("records"), batch_size):
            run_cypher(query, rows=b)

nodes_df = build_nodes(triples_df)
if nodes_df.empty:
    raise RuntimeError("nodes_df rỗng - kiểm tra lại bước extraction/entity resolution.")

t0 = time.perf_counter()
bulk_insert_nodes(nodes_df, batch_size=1000)
bulk_insert_edges(triples_df, batch_size=1000)
_ingest_s = time.perf_counter() - t0

print(f"Bulk insert xong sau {_ingest_s:.1f}s "
      f"| nodes={len(nodes_df):,} | edges={len(triples_df):,}")
print(nodes_df.type.value_counts().to_dict())

RUN_STATE["ingest_graph"] = {
    "nodes": int(len(nodes_df)),
    "edges": int(len(triples_df)),
    "seconds": round(_ingest_s, 1),
    "node_types": nodes_df.type.value_counts().to_dict(),
}
nodes_df.to_csv(OUTPUT_DIR / "nodes.csv", index=False)
triples_df.to_csv(OUTPUT_DIR / "triples_canonical.csv", index=False)
display(nodes_df.head())

In [ ]:
#@title 2.4 — Sanity checks
def graph_checks():
    invalid = run_cypher("""
    MATCH ()-[r]->()
    WHERE r.source_chunk_id IS NULL OR r.published_date IS NULL
    RETURN count(r) AS n
    """)[0]["n"]

    counts = {
        "nodes": run_cypher("MATCH (n:Entity) RETURN count(n) AS n")[0]["n"],
        "edges": run_cypher("MATCH ()-[r]->() RETURN count(r) AS n")[0]["n"],
        "invalid_provenance_edges": invalid,
    }
    print(counts)
    assert invalid == 0

    top = pd.DataFrame(run_cypher("""
    MATCH (n:Entity)
    OPTIONAL MATCH (n)-[r]-()
    WITH n, count(r) AS degree
    RETURN n.id AS id, n.name AS name, n.entity_type AS type, degree
    ORDER BY degree DESC LIMIT 15
    """))
    display(top)
    return counts, top

graph_counts, top_degree_df = graph_checks()
RUN_STATE["graph_checks"] = {
    "counts": graph_counts,
    "top_degree": top_degree_df.head(5).to_dict("records") if len(top_degree_df) else [],
}
top_degree_df.to_csv(OUTPUT_DIR / "top_degree_nodes.csv", index=False)

# PHẦN 3 — FLAT RAG & HYBRID GRAPHRAG (45–75')

## Flat RAG baseline
Dùng cùng embedding/generator để comparison tập trung vào retrieval architecture.

In [ ]:
#@title 3.1 — Flat RAG
flat_index = None
flat_store = None
entity_match_vectors = None
entity_match_store = None

def build_flat_index(chunks_df):
    global flat_index, flat_store
    vecs = get_embedder().encode(
        chunks_df.text.fillna("").tolist(),
        batch_size=128, show_progress_bar=True,
        normalize_embeddings=True
    ).astype("float32")

    flat_index = faiss.IndexFlatIP(vecs.shape[1])
    flat_index.add(vecs)
    flat_store = chunks_df.reset_index(drop=True).copy()
    print("Flat vectors:", flat_index.ntotal)

def retrieve_flat_context(query, k=6):
    qv = get_embedder().encode(
        [query], normalize_embeddings=True, show_progress_bar=False
    ).astype("float32")
    scores, ids = flat_index.search(qv, min(k, flat_index.ntotal))

    rows = []
    for score, idx in zip(scores[0], ids[0]):
        if idx < 0:
            continue
        r = flat_store.iloc[int(idx)]
        rows.append({
            "score":float(score), "chunk_id":r.chunk_id,
            "published_date":r.published_date, "text":r.text
        })

    df = pd.DataFrame(rows)
    context = "\n\n".join(
        f"[chunk_id={r.chunk_id} | date={r.published_date} | score={r.score:.3f}]\n{r.text}"
        for r in df.itertuples(index=False)
    )
    return context, df

build_flat_index(chunks_df)
_demo_ctx, _demo_docs = retrieve_flat_context("Which company invested in an AI startup?", k=3)
display(_demo_docs[["score", "chunk_id", "published_date"]])
RUN_STATE["flat_index"] = {"vectors": int(flat_index.ntotal), "embed_model": EMBED_MODEL}

## Graph retrieval flow
1. LLM trích seed entities.
2. Match seed trong Neo4j; fuzzy fallback bằng embedding.
3. BFS tối đa `max_hops`.
4. Nếu node degree > 100 → chỉ lấy tối đa 50 edge mới nhất.
5. Global edge cap để tránh context explosion.
6. Textualize subgraph có provenance.

In [ ]:
#@title 3.2 — Seed matching
SEED_SYSTEM = """
Extract useful seed entities for graph retrieval.
Allowed types: Company, Person, Technology.
Do not answer the question. Return strict JSON only.
""".strip()

def extract_seeds(query):
    obj, _ = groq_json(SEED_SYSTEM, f"""
Question: {query}
Return {{"seeds":[{{"name":"...","type":"Company|Person|Technology|null"}}]}}
""")
    return [
        {"name":norm_space(x.get("name")),
         "type":x.get("type") if x.get("type") in ALLOWED_NODE_TYPES else None}
        for x in obj.get("seeds", [])
        if norm_space(x.get("name"))
    ]

def build_entity_matcher(nodes_df):
    global entity_match_vectors, entity_match_store
    entity_match_store = nodes_df.reset_index(drop=True).copy()
    entity_match_vectors = get_embedder().encode(
        entity_match_store.name.tolist(),
        batch_size=128, show_progress_bar=False,
        normalize_embeddings=True
    ).astype("float32")

def match_seeds(query, fuzzy_threshold=0.66):
    matched = []
    for seed in extract_seeds(query):
        exact = run_cypher("""
        MATCH (n:Entity)
        WHERE (n.name_norm=$name OR $name IN coalesce(n.aliases_norm,[]))
          AND ($typ IS NULL OR n.entity_type=$typ)
        RETURN n.id AS id, n.name AS name, n.entity_type AS type
        LIMIT 5
        """, name=norm_entity(seed["name"]), typ=seed["type"])

        if exact:
            matched += exact
            continue

        if entity_match_vectors is None:
            continue

        mask = np.ones(len(entity_match_store), dtype=bool)
        if seed["type"]:
            mask = entity_match_store.type.eq(seed["type"]).to_numpy()
        idxs = np.flatnonzero(mask)
        if not len(idxs):
            continue

        qv = get_embedder().encode(
            [seed["name"]], normalize_embeddings=True, show_progress_bar=False
        ).astype("float32")[0]
        sims = entity_match_vectors[idxs] @ qv
        j = int(np.argmax(sims))
        if float(sims[j]) >= fuzzy_threshold:
            r = entity_match_store.iloc[int(idxs[j])]
            matched.append({"id":r.id,"name":r.name,"type":r.type})

    return list({x["id"]: x for x in matched}.values())

build_entity_matcher(nodes_df)
print("Entity matcher vectors:", entity_match_vectors.shape)
_demo_seeds = match_seeds("Which technology did Google develop?")
print("Seed matched:", _demo_seeds)

In [ ]:
#@title 3.3 — Graph traversal + super-node mitigation
SUPER_NODE_DEGREE = 100
SUPER_NODE_EDGE_CAP = 50
GLOBAL_EDGE_CAP = 250
MAX_GRAPH_CONTEXT_CHARS = 14000
MAX_EXPANDED_NODES = 60      # tran so node duoc mo rong trong 1 lan truy van

def node_degree(node_id):
    return int(run_cypher("""
    MATCH (n:Entity {id:$id})
    OPTIONAL MATCH (n)-[r]-()
    RETURN count(r) AS degree
    """, id=node_id)[0]["degree"])

def degree_and_edges(node_id, limit, super_degree, super_cap):
    """Do degree va lay canh trong MOT round-trip.

    Moi round-trip toi AuraDB ton ~100-200ms; BFS 2 hop cham hang chuc node nen
    tach lam 2 query se gap doi do tre ma khong them thong tin gi.
    Chinh sach super-node duoc ap o phia Python: danh sach canh da sap xep
    published_date DESC nen cat top-N van dung "N canh moi nhat".
    """
    rows = run_cypher("""
    MATCH (n:Entity {id:$id})
    OPTIONAL MATCH (n)-[deg]-()
    WITH n, count(deg) AS degree
    CALL {
      WITH n
      MATCH (n)-[r]-(m:Entity)
      RETURN
        startNode(r).id AS source_id,
        startNode(r).name AS source_name,
        startNode(r).entity_type AS source_type,
        type(r) AS relation,
        endNode(r).id AS target_id,
        endNode(r).name AS target_name,
        endNode(r).entity_type AS target_type,
        r.source_chunk_id AS source_chunk_id,
        r.published_date AS published_date,
        r.evidence AS evidence,
        m.id AS neighbor_id
      ORDER BY coalesce(r.published_date,'') DESC
      LIMIT $limit
    }
    RETURN degree, source_id, source_name, source_type, relation,
           target_id, target_name, target_type, source_chunk_id,
           published_date, evidence, neighbor_id
    """, id=node_id, limit=int(limit))

    if not rows:
        return 0, int(limit), []

    degree = int(rows[0]["degree"])
    edges = [{k: v for k, v in r.items() if k != "degree"} for r in rows]
    eff_limit = int(limit)
    if degree > super_degree:
        eff_limit = min(int(limit), int(super_cap))
        edges = edges[:eff_limit]
    return degree, eff_limit, edges

def recent_edges(node_id, limit):
    return run_cypher("""
    MATCH (n:Entity {id:$id})
    MATCH (n)-[r]-(m:Entity)
    RETURN
      startNode(r).id AS source_id,
      startNode(r).name AS source_name,
      startNode(r).entity_type AS source_type,
      type(r) AS relation,
      endNode(r).id AS target_id,
      endNode(r).name AS target_name,
      endNode(r).entity_type AS target_type,
      r.source_chunk_id AS source_chunk_id,
      r.published_date AS published_date,
      r.evidence AS evidence,
      m.id AS neighbor_id
    ORDER BY coalesce(r.published_date,'') DESC
    LIMIT $limit
    """, id=node_id, limit=int(limit))

def textualize(edges):
    edges = sorted(edges, key=lambda e:e.get("published_date") or "", reverse=True)
    lines, used = [], 0
    for e in edges:
        line = (
            f"{e['source_name']} [{e['source_type']}] -{e['relation']}-> "
            f"{e['target_name']} [{e['target_type']}] "
            f"| date={e.get('published_date') or 'unknown'} "
            f"| chunk={e.get('source_chunk_id') or 'unknown'}"
        )
        if e.get("evidence"):
            line += f" | evidence={norm_space(e['evidence'])}"
        if used + len(line) + 1 > MAX_GRAPH_CONTEXT_CHARS:
            break
        lines.append(line)
        used += len(line) + 1
    return "\n".join(lines)

def retrieve_graph_context(query, max_hops=2, edge_limit=50, return_debug=False):
    seeds = match_seeds(query)
    if not seeds:
        out = {"context":"","edges":pd.DataFrame(),
               "diagnostics":{"reason":"NO_SEED","supernode_events":[]}}
        return out if return_debug else ""

    frontier = deque((x["id"],0) for x in seeds)
    expanded, seen_edges, collected = set(), set(), []
    supernode_events = []

    while frontier and len(collected) < GLOBAL_EDGE_CAP and len(expanded) < MAX_EXPANDED_NODES:
        node_id, hop = frontier.popleft()
        if node_id in expanded or hop >= max_hops:
            continue
        expanded.add(node_id)

        degree, limit, node_edges = degree_and_edges(
            node_id, int(edge_limit), SUPER_NODE_DEGREE, SUPER_NODE_EDGE_CAP
        )
        if degree > SUPER_NODE_DEGREE:
            supernode_events.append({"node_id":node_id,"degree":degree,"limit":limit})

        for e in node_edges:
            key = (e["source_id"],e["relation"],e["target_id"],e["source_chunk_id"])
            if key in seen_edges:
                continue
            seen_edges.add(key)
            collected.append(e)
            if len(collected) >= GLOBAL_EDGE_CAP:
                break

            nb = e.get("neighbor_id")
            if nb and nb not in expanded and hop + 1 < max_hops:
                frontier.append((nb, hop+1))

    out = {
        "context": textualize(collected),
        "edges": pd.DataFrame(collected),
        "diagnostics": {
            "matched_seeds": seeds,
            "expanded_nodes": len(expanded),
            "collected_edges": len(collected),
            "supernode_events": supernode_events,
        }
    }
    return out if return_debug else out["context"]

In [ ]:
#@title 3.4 — Flat answer vs Hybrid GraphRAG answer
ANSWER_SYSTEM = """
Answer only from supplied context.
Be concise but complete. Do not invent facts.
Cite provenance inline as [chunk_id=...] whenever possible.
If evidence is insufficient or conflicting, say so.
""".strip()

def generate_answer(question, context):
    prompt = f"QUESTION:\n{question}\n\nCONTEXT:\n{context}\n\nANSWER:"
    t0 = time.perf_counter()
    text, usage = groq_chat(
        [{"role":"system","content":ANSWER_SYSTEM},
         {"role":"user","content":prompt}],
        model=GROQ_MODEL
    )
    return {
        "answer": text.strip(),
        "latency_s": time.perf_counter()-t0,
        "total_tokens": usage.get("total_tokens"),
    }

def answer_flat_rag(question):
    context, retrieved = retrieve_flat_context(question, k=6)
    out = generate_answer(question, context)
    out.update({"context":context,"retrieved":retrieved})
    return out

def answer_graph_rag(question):
    g = retrieve_graph_context(question, max_hops=2, edge_limit=50, return_debug=True)
    vctx, vdocs = retrieve_flat_context(question, k=4)
    context = f"=== GRAPH ===\n{g['context']}\n\n=== VECTOR ===\n{vctx}"
    out = generate_answer(question, context)
    out.update({"context":context,"graph_debug":g,"vector_docs":vdocs})
    return out

In [ ]:
#@title 3.5 — Smoke test: Flat RAG vs Hybrid GraphRAG trên 1 câu hỏi
SMOKE_QUESTION = "Which company invested in or acquired an AI company, and when was it reported?"

_flat = answer_flat_rag(SMOKE_QUESTION)
_graph = answer_graph_rag(SMOKE_QUESTION)

print("=" * 30, "FLAT RAG", "=" * 30)
print(_flat["answer"])
print(f"\n[latency={_flat['latency_s']:.2f}s | tokens={_flat['total_tokens']}]")

print("\n" + "=" * 30, "HYBRID GRAPHRAG", "=" * 30)
print(_graph["answer"])
print(f"\n[latency={_graph['latency_s']:.2f}s | tokens={_graph['total_tokens']}]")
print("\nGraph diagnostics:", {
    k: v for k, v in _graph["graph_debug"]["diagnostics"].items() if k != "matched_seeds"
})
print("Seeds:", _graph["graph_debug"]["diagnostics"].get("matched_seeds"))
print("\n--- 800 ký tự đầu của graph context ---")
print(_graph["graph_debug"]["context"][:800] or "(rỗng - không match được seed nào)")

# PHẦN 4 — GOLDEN DATASET & LLM-AS-A-JUDGE (75–105')

## Golden schema
`id`, `group`, `question`, `reference_answer`, optional `reference_evidence`.

Notebook có 5 câu starter. Các câu phụ thuộc data dump phải điền gold answer thật trước final evaluation.

In [ ]:
#@title 4.1 — Golden Dataset: starter + gold answer khai thác từ graph thật
GOLDEN_PATH = str(WORK_DIR / "golden_dataset.csv")
REGENERATE_GOLDEN = True   # False -> dùng lại file CSV đã chỉnh tay

starter_golden = pd.DataFrame([
    {
        "id": "G01", "group": "factoid",
        "question": "Who was the CEO of Hugging Face in 2023?",
        "reference_answer": "Clement Delangue",
        "reference_evidence": "External anchor: kiểm tra lại nếu data dump không chứa thông tin này.",
    },
])

# --------------------------------------------------------------------------
# Các câu G02+ phải có gold answer THẬT. Thay vì đoán, ta khai thác trực tiếp
# từ knowledge graph vừa nạp: mỗi câu hỏi đều gắn với cạnh/đường đi có provenance.
# --------------------------------------------------------------------------
FACTOID_TEMPLATES = {
    "ACQUIRED":       ("According to the ingested tech news, which company did {a} acquire? Give the reported date.", "target"),
    "INVESTED_IN":    ("According to the ingested tech news, which organization did {a} invest in? Give the reported date.", "target"),
    "DEVELOPED":      ("According to the ingested tech news, which technology or product did {a} develop?", "target"),
    "PARTNERED_WITH": ("According to the ingested tech news, which organization did {a} partner with?", "target"),
    "USES":           ("According to the ingested tech news, which technology does {a} use?", "target"),
    "FOUNDED":        ("According to the ingested tech news, who or what founded {b}?", "source"),
    "LEADS":          ("According to the ingested tech news, who leads {b}?", "source"),
    "WORKED_AT":      ("According to the ingested tech news, where did {a} work?", "target"),
}

def mine_factoid_questions(n=3):
    rows = run_cypher("""
    MATCH (a:Entity)-[r]->(b:Entity)
    WHERE coalesce(r.published_date,'') <> '' AND coalesce(r.evidence,'') <> ''
    RETURN a.name AS a_name, type(r) AS rel, b.name AS b_name,
           r.published_date AS date, r.evidence AS evidence,
           r.source_chunk_id AS chunk, coalesce(r.confidence,0.0) AS conf
    ORDER BY conf DESC, date DESC
    LIMIT 200
    """)
    out, used_rel = [], set()
    for x in rows:
        if len(out) >= n:
            break
        if x["rel"] not in FACTOID_TEMPLATES or x["rel"] in used_rel:
            continue
        tmpl, answer_side = FACTOID_TEMPLATES[x["rel"]]
        answer = x["b_name"] if answer_side == "target" else x["a_name"]
        used_rel.add(x["rel"])
        out.append({
            "group": "factoid",
            "question": tmpl.format(a=x["a_name"], b=x["b_name"]),
            "reference_answer": f"{answer} (reported {x['date']}).",
            "reference_evidence": f"{x['a_name']} -{x['rel']}-> {x['b_name']} | chunk={x['chunk']} | {norm_space(x['evidence'])[:180]}",
        })
    return out

def mine_multihop_questions(n=3):
    rows = run_cypher("""
    MATCH (a:Entity)-[r1]->(b:Entity)-[r2]->(c:Entity)
    WHERE a <> c AND coalesce(r1.published_date,'') <> '' AND coalesce(r2.published_date,'') <> ''
    RETURN a.name AS a_name, type(r1) AS rel1, b.name AS b_name, type(r2) AS rel2,
           c.name AS c_name, r1.published_date AS d1, r2.published_date AS d2,
           r1.source_chunk_id AS chunk1, r2.source_chunk_id AS chunk2
    LIMIT 200
    """)
    out, seen = [], set()
    for x in rows:
        if len(out) >= n:
            break
        key = (x["a_name"], x["rel1"], x["rel2"])
        if key in seen:
            continue
        seen.add(key)
        out.append({
            "group": "multi-hop",
            "question": (
                f"Starting from {x['a_name']}, follow the reported relation {x['rel1']} and then {x['rel2']}. "
                f"Which intermediate entity and which final entity do you reach? Give both reported dates."
            ),
            "reference_answer": (
                f"Intermediate: {x['b_name']}; final: {x['c_name']}. "
                f"Chain: {x['a_name']} -{x['rel1']}({x['d1']})-> {x['b_name']} -{x['rel2']}({x['d2']})-> {x['c_name']}."
            ),
            "reference_evidence": f"chunks={x['chunk1']}, {x['chunk2']}",
        })
    return out

def mine_crossdoc_questions(n=2):
    rows = run_cypher("""
    MATCH (a:Entity)-[r]->(b:Entity)
    WITH a, b, type(r) AS rel,
         collect(DISTINCT r.source_chunk_id) AS chunks,
         collect(DISTINCT r.published_date) AS dates
    WHERE size(chunks) >= 2
    RETURN a.name AS a_name, b.name AS b_name, rel, chunks, dates
    ORDER BY size(chunks) DESC
    LIMIT 50
    """)
    if not rows:
        # Fallback: một thực thể xuất hiện trong >= 2 chunk với nhiều láng giềng khác nhau.
        rows2 = run_cypher("""
        MATCH (a:Entity)-[r]->(b:Entity)
        WITH a, collect(DISTINCT r.source_chunk_id) AS chunks, collect(DISTINCT b.name) AS nbrs
        WHERE size(chunks) >= 2 AND size(nbrs) >= 2
        RETURN a.name AS a_name, chunks, nbrs
        ORDER BY size(chunks) DESC LIMIT 10
        """)
        return [{
            "group": "cross-doc",
            "question": (
                f"Several articles mention {x['a_name']}. Summarize the relationships reported for "
                f"{x['a_name']} across those articles and cite the chunk ids."
            ),
            "reference_answer": f"{x['a_name']} liên quan tới: {', '.join(map(str, x['nbrs'][:6]))}.",
            "reference_evidence": f"chunks={', '.join(map(str, x['chunks'][:6]))}",
        } for x in rows2[:n]]

    out = []
    for x in rows[:n]:
        dates = [d for d in x["dates"] if d]
        out.append({
            "group": "cross-doc",
            "question": (
                f"Multiple news chunks report a relationship between {x['a_name']} and {x['b_name']}. "
                f"Summarize what is reported, list the reported dates and cite the chunk ids."
            ),
            "reference_answer": (
                f"{x['a_name']} -{x['rel']}-> {x['b_name']}, được báo cáo trong {len(x['chunks'])} chunk "
                f"với các ngày: {', '.join(map(str, sorted(set(dates)))) or 'không rõ'}."
            ),
            "reference_evidence": f"chunks={', '.join(map(str, x['chunks'][:6]))}",
        })
    return out

def mine_golden_from_graph():
    mined = mine_factoid_questions(3) + mine_multihop_questions(3) + mine_crossdoc_questions(2)
    df = pd.DataFrame(mined)
    if df.empty:
        return df
    df.insert(0, "id", [f"G{i:02d}" for i in range(2, 2 + len(df))])
    return df

def validate_golden(df, require_answers=True):
    required = {"id", "group", "question", "reference_answer"}
    if not required.issubset(df.columns):
        raise ValueError(f"Missing columns: {required - set(df.columns)}")
    if require_answers and df.reference_answer.fillna("").str.strip().eq("").any():
        display(df[df.reference_answer.fillna("").str.strip().eq("")][["id", "question"]])
        raise ValueError("Điền reference_answer trước final evaluation.")
    groups = set(df.group.unique())
    missing_groups = {"factoid", "multi-hop", "cross-doc"} - groups
    if missing_groups:
        raise ValueError(f"Thiếu nhóm câu hỏi: {missing_groups}")
    if len(df) < 5:
        raise ValueError("Golden Dataset cần ít nhất 5 câu.")
    print(f"Golden Dataset hợp lệ: {len(df)} câu | nhóm: {sorted(groups)}")

if GOLDEN_SOURCE_CSV and Path(GOLDEN_SOURCE_CSV).exists():
    # Ưu tiên tuyệt đối cho Golden Dataset của giảng viên: gold answer đã được
    # neo vào đúng các dòng dữ liệu gốc nên không được sinh lại.
    golden_df = pd.read_csv(GOLDEN_SOURCE_CSV)
    keep = [c for c in ["id", "group", "question", "reference_answer", "reference_evidence"]
            if c in golden_df.columns]
    golden_df = golden_df[keep].copy()
    print(f"Dùng Golden Dataset của giảng viên: {GOLDEN_SOURCE_CSV} ({len(golden_df)} câu)")
    golden_df.to_csv(GOLDEN_PATH, index=False)
elif REGENERATE_GOLDEN or not Path(GOLDEN_PATH).exists():
    mined_golden = mine_golden_from_graph()
    if mined_golden.empty:
        raise RuntimeError("Không khai thác được câu hỏi từ graph - graph có thể rỗng.")
    golden_df = pd.concat([starter_golden, mined_golden], ignore_index=True)
    golden_df.to_csv(GOLDEN_PATH, index=False)
else:
    golden_df = pd.read_csv(GOLDEN_PATH)

validate_golden(golden_df, require_answers=True)
golden_df.to_csv(OUTPUT_DIR / "golden_dataset.csv", index=False)
RUN_STATE["golden"] = {
    "n_questions": int(len(golden_df)),
    "by_group": golden_df.group.value_counts().to_dict(),
}
display(golden_df)

In [ ]:
#@title 4.2 — LLM-as-a-Judge
JUDGE_SYSTEM = """
You are a strict evaluator of RAG answers.
Score 1-5:
- comprehensiveness
- faithfulness to supplied candidate context
- multi_hop_reasoning accuracy
Use the reference answer as correctness anchor.
Return strict JSON only.
""".strip()

def judge_json(system, user):
    if not JUDGE_MODEL:
        raise RuntimeError("Thiếu JUDGE_MODEL.")

    if JUDGE_PROVIDER == "groq":
        return groq_json(system, user, model=JUDGE_MODEL)[0]

    if JUDGE_PROVIDER == "openai":
        if not OPENAI_API_KEY:
            raise RuntimeError("Thiếu OPENAI_API_KEY.")
        from openai import OpenAI
        client = OpenAI(api_key=OPENAI_API_KEY)
        resp = client.chat.completions.create(
            model=JUDGE_MODEL,
            messages=[{"role":"system","content":system},
                      {"role":"user","content":user}],
            temperature=0.0,
            response_format={"type":"json_object"}
        )
        return parse_json_object(resp.choices[0].message.content)

    raise ValueError("JUDGE_PROVIDER must be openai or groq.")

def judge_answer(question, reference, answer, context):
    prompt = f"""
QUESTION:
{question}

REFERENCE:
{reference}

CANDIDATE:
{answer}

CANDIDATE CONTEXT:
{context[:18000]}

Return:
{{
 "comprehensiveness":1,
 "faithfulness":1,
 "multi_hop_reasoning":1,
 "rationale":"2-5 sentences"
}}
"""
    obj = judge_json(JUDGE_SYSTEM, prompt)
    out = {}
    for k in ["comprehensiveness","faithfulness","multi_hop_reasoning"]:
        out[k] = max(1, min(5, int(obj.get(k,1))))
    out["rationale"] = norm_space(obj.get("rationale"))
    return out

def judge_answer_safe(question, reference, answer, context, max_retries=3):
    """Judge có retry. Nếu vẫn lỗi -> trả về điểm 1 + rationale ghi rõ lỗi (không làm gãy eval)."""
    last = None
    for attempt in range(max_retries):
        try:
            return judge_answer(question, reference, answer, context)
        except Exception as e:
            last = e
            time.sleep(min(15, 2 ** attempt + random.random()))
    return {
        "comprehensiveness": 1, "faithfulness": 1, "multi_hop_reasoning": 1,
        "rationale": f"JUDGE_FAILED: {last}",
    }

In [ ]:
# === LOCAL RUN OVERRIDE: cache cho judge ===
_raw_judge_json = judge_json

def judge_json(system, user):
    key = _ckey("judge", JUDGE_PROVIDER, JUDGE_MODEL, system, user)
    hit = _cget(key)
    if hit is not None:
        return hit
    out = _raw_judge_json(system, user)
    _cput(key, out)
    return out
print("Judge cache da bat.")

In [ ]:
#@title 4.3 — Evaluation runner + checkpoint
CHECKPOINT = str(WORK_DIR / "graphrag_eval_checkpoint.csv")

def run_evaluation(golden_df):
    rows = []
    for q in tqdm(golden_df.itertuples(index=False), total=len(golden_df), desc="Evaluation"):
        flat = answer_flat_rag(q.question)
        graph = answer_graph_rag(q.question)

        jf = judge_answer_safe(q.question, q.reference_answer, flat["answer"], flat["context"])
        jg = judge_answer_safe(q.question, q.reference_answer, graph["answer"], graph["context"])

        rows.append({
            "id":q.id, "group":q.group, "question":q.question,
            "reference_answer":q.reference_answer,
            "flat_answer":flat["answer"], "graph_answer":graph["answer"],
            "flat_comprehensiveness":jf["comprehensiveness"],
            "graph_comprehensiveness":jg["comprehensiveness"],
            "flat_faithfulness":jf["faithfulness"],
            "graph_faithfulness":jg["faithfulness"],
            "flat_multi_hop_reasoning":jf["multi_hop_reasoning"],
            "graph_multi_hop_reasoning":jg["multi_hop_reasoning"],
            "flat_latency_s":flat["latency_s"],
            "graph_latency_s":graph["latency_s"],
            "flat_total_tokens":flat.get("total_tokens"),
            "graph_total_tokens":graph.get("total_tokens"),
            "flat_judge_rationale":jf["rationale"],
            "graph_judge_rationale":jg["rationale"],
            "graph_supernode_events":len(
                graph["graph_debug"]["diagnostics"].get("supernode_events",[])
            ),
            "graph_seeds": len(graph["graph_debug"]["diagnostics"].get("matched_seeds",[])),
            "graph_edges_used": int(graph["graph_debug"]["diagnostics"].get("collected_edges",0)),
            "flat_context_chars": len(flat["context"]),
            "graph_context_chars": len(graph["context"]),
        })
        pd.DataFrame(rows).to_csv(CHECKPOINT, index=False)
    return pd.DataFrame(rows)

validate_golden(golden_df, require_answers=True)
eval_results_df = run_evaluation(golden_df)
print(f"Đã đánh giá {len(eval_results_df)} câu. Checkpoint: {CHECKPOINT}")
display(eval_results_df[[
    "id", "group",
    "flat_comprehensiveness", "graph_comprehensiveness",
    "flat_faithfulness", "graph_faithfulness",
    "flat_multi_hop_reasoning", "graph_multi_hop_reasoning",
    "flat_latency_s", "graph_latency_s",
    "flat_total_tokens", "graph_total_tokens",
]])

In [ ]:
#@title 4.4 — Comparison table + export
def comparison_table(eval_df):
    metric_map = {
        "Comprehensiveness":("flat_comprehensiveness","graph_comprehensiveness"),
        "Faithfulness":("flat_faithfulness","graph_faithfulness"),
        "Multi-hop reasoning":("flat_multi_hop_reasoning","graph_multi_hop_reasoning"),
        "Latency (s)":("flat_latency_s","graph_latency_s"),
        "Token usage":("flat_total_tokens","graph_total_tokens"),
    }

    rows = []
    for group, g in eval_df.groupby("group"):
        for metric, (fc,gc) in metric_map.items():
            f = pd.to_numeric(g[fc], errors="coerce").mean()
            gr = pd.to_numeric(g[gc], errors="coerce").mean()

            if metric in {"Latency (s)","Token usage"}:
                comment = "Flat RAG thường rẻ/nhanh hơn." if f < gr else "GraphRAG không đắt hơn trong sample này."
            else:
                delta = gr - f
                if delta >= .75:
                    comment = "GraphRAG cải thiện rõ; kiểm tra rationale và provenance."
                elif delta <= -.5:
                    comment = "Flat RAG tốt hơn; graph extraction/retrieval có thể gây mất thông tin hoặc nhiễu."
                else:
                    comment = "Hai phương pháp gần nhau."

            rows.append({
                "Loại câu hỏi":group, "Metric":metric,
                "Flat RAG":round(f,3) if pd.notna(f) else np.nan,
                "GraphRAG":round(gr,3) if pd.notna(gr) else np.nan,
                "Nhận xét phân tích":comment
            })
    return pd.DataFrame(rows)

comparison_df = comparison_table(eval_results_df)
display(comparison_df)

# Bảng tổng (không tách theo nhóm) để đọc nhanh trong báo cáo.
overall_rows = []
for metric, (fc, gc) in {
    "Comprehensiveness": ("flat_comprehensiveness", "graph_comprehensiveness"),
    "Faithfulness": ("flat_faithfulness", "graph_faithfulness"),
    "Multi-hop reasoning": ("flat_multi_hop_reasoning", "graph_multi_hop_reasoning"),
    "Latency (s)": ("flat_latency_s", "graph_latency_s"),
    "Token usage": ("flat_total_tokens", "graph_total_tokens"),
}.items():
    f = pd.to_numeric(eval_results_df[fc], errors="coerce").mean()
    g = pd.to_numeric(eval_results_df[gc], errors="coerce").mean()
    overall_rows.append({
        "Metric": metric,
        "Flat RAG": round(f, 3) if pd.notna(f) else np.nan,
        "GraphRAG": round(g, 3) if pd.notna(g) else np.nan,
        "Delta (Graph - Flat)": round(g - f, 3) if pd.notna(f) and pd.notna(g) else np.nan,
    })
overall_df = pd.DataFrame(overall_rows)
print("=== Tổng hợp toàn bộ Golden Dataset ===")
display(overall_df)

eval_results_df.to_csv(OUTPUT_DIR / "graphrag_eval_results.csv", index=False)
comparison_df.to_csv(OUTPUT_DIR / "graphrag_vs_flatrag_summary.csv", index=False)
overall_df.to_csv(OUTPUT_DIR / "graphrag_vs_flatrag_overall.csv", index=False)
# Bản sao ở WORK_DIR (/content trên Colab) để tải về trực tiếp.
eval_results_df.to_csv(WORK_DIR / "graphrag_eval_results.csv", index=False)
comparison_df.to_csv(WORK_DIR / "graphrag_vs_flatrag_summary.csv", index=False)

RUN_STATE["evaluation"] = {
    "overall": overall_df.to_dict("records"),
    "by_group": comparison_df.to_dict("records"),
}
print("Đã xuất:", [p.name for p in sorted(OUTPUT_DIR.glob("*.csv"))])

# PHẦN 5 — FAILURE-MODE CHECKS & SUBMISSION (105–120')

Bắt buộc chứng minh:
1. Edge provenance không thiếu.
2. Entity Resolution có audit.
3. Super-node degree > 100 chỉ expand tối đa 50 edge.
4. Có comparison table.

In [ ]:
#@title 5.1 — Super-node check + entity audit
def test_supernode_policy():
    rows = run_cypher("""
    MATCH (n:Entity)-[r]-()
    WITH n, count(r) AS degree
    ORDER BY degree DESC LIMIT 1
    RETURN n.id AS id, n.name AS name, degree
    """)
    if not rows:
        print("Graph empty.")
        return

    n = rows[0]
    limit = 50 if n["degree"] > SUPER_NODE_DEGREE else 1000
    edges = recent_edges(n["id"], limit)
    print(n, "fetched=", len(edges))
    if n["degree"] > SUPER_NODE_DEGREE:
        assert len(edges) <= 50
        print("✅ Super-node cap OK.")

def show_resolution_audit(audit_df):
    if audit_df.empty:
        print("No audit rows.")
        return
    display(
        audit_df.sort_values("similarity", ascending=False).head(30)
    )
    print("High-similarity rejected pairs:")
    display(
        audit_df[audit_df.decision=="REJECT_GUARD"]
        .sort_values("similarity", ascending=False)
        .head(20)
    )

def test_edge_provenance():
    n = run_cypher("""
    MATCH ()-[r]->()
    WHERE r.source_chunk_id IS NULL OR r.published_date IS NULL OR r.source_chunk_id = ''
    RETURN count(r) AS n
    """)[0]["n"]
    empty_date = run_cypher("""
    MATCH ()-[r]->() WHERE r.published_date = '' RETURN count(r) AS n
    """)[0]["n"]
    assert n == 0, f"Còn {n} cạnh thiếu provenance!"
    print("Edge provenance OK: 0 cạnh thiếu source_chunk_id/published_date.")
    if empty_date:
        print(f"Cảnh báo: {empty_date} cạnh có published_date rỗng (bài gốc không có ngày xuất bản).")

def top_supernodes(k=3):
    return pd.DataFrame(run_cypher("""
    MATCH (n:Entity)-[r]-()
    WITH n, count(r) AS degree
    RETURN n.name AS name, n.entity_type AS type, degree
    ORDER BY degree DESC LIMIT $k
    """, k=int(k)))

test_edge_provenance()
test_supernode_policy()

top3_df = top_supernodes(3)
print("Top 3 super-node theo degree:")
display(top3_df)

show_resolution_audit(entity_resolution_audit_df)

RUN_STATE["failure_checks"] = {
    "provenance_ok": True,
    "top3_supernodes": top3_df.to_dict("records") if len(top3_df) else [],
    "super_node_degree": SUPER_NODE_DEGREE,
    "super_node_edge_cap": SUPER_NODE_EDGE_CAP,
    "global_edge_cap": GLOBAL_EDGE_CAP,
    "rejected_high_sim": entity_resolution_audit_df[
        (entity_resolution_audit_df.decision == "REJECT_GUARD")
    ].sort_values("similarity", ascending=False).head(5).to_dict("records")
      if len(entity_resolution_audit_df) else [],
}

In [ ]:
#@title 5.1b — Failure analysis: truy vết ca Flat thắng / Graph thắng
def quality_score(row, prefix):
    return float(np.mean([
        row[f"{prefix}_comprehensiveness"],
        row[f"{prefix}_faithfulness"],
        row[f"{prefix}_multi_hop_reasoning"],
    ]))

fa = eval_results_df.copy()
fa["flat_quality"] = fa.apply(lambda r: quality_score(r, "flat"), axis=1)
fa["graph_quality"] = fa.apply(lambda r: quality_score(r, "graph"), axis=1)
fa["delta"] = fa.graph_quality - fa.flat_quality

display(fa[["id", "group", "flat_quality", "graph_quality", "delta",
            "graph_seeds", "graph_edges_used", "graph_supernode_events"]]
        .sort_values("delta", ascending=False))

graph_wins = fa.sort_values("delta", ascending=False).head(1)
flat_wins = fa.sort_values("delta", ascending=True).head(1)

def case_block(row, title):
    r = row.iloc[0]
    return f"""### {title}

- **Câu hỏi ({r['id']} / {r['group']}):** {r['question']}
- **Reference:** {r['reference_answer']}
- **Điểm Flat:** {r['flat_quality']:.2f} · **Điểm Graph:** {r['graph_quality']:.2f} · **Delta:** {r['delta']:+.2f}
- **Tín hiệu retrieval:** seed khớp = {r['graph_seeds']}, cạnh dùng = {r['graph_edges_used']}, super-node event = {r['graph_supernode_events']}, độ dài context flat/graph = {r['flat_context_chars']}/{r['graph_context_chars']} ký tự

**Câu trả lời Flat RAG**

> {str(r['flat_answer'])[:900]}

**Câu trả lời GraphRAG**

> {str(r['graph_answer'])[:900]}

**Judge rationale (flat):** {str(r['flat_judge_rationale'])[:600]}

**Judge rationale (graph):** {str(r['graph_judge_rationale'])[:600]}

**Root-cause analysis**

1. *Triệu chứng:* chênh lệch điểm {r['delta']:+.2f} giữa hai kiến trúc trong khi generator và embedding **hoàn toàn giống nhau**, nên nguyên nhân nằm ở tầng **retrieval**, không phải ở model sinh.
2. *Bước hỏng:* {"seed matching trả về " + str(r['graph_seeds']) + " seed nên BFS không có điểm xuất phát — toàn bộ phần GRAPH của context rỗng, GraphRAG tụt về đúng bằng vector search với k nhỏ hơn" if r['graph_seeds'] == 0 else "seed matching hoạt động; điểm nghi vấn tiếp theo là số cạnh thu được (" + str(r['graph_edges_used']) + ") và ngưỡng cắt super-node"}.
3. *Bằng chứng:* đối chiếu `graph_debug['diagnostics']` của câu hỏi này và các trích dẫn `[chunk_id=...]` trong câu trả lời để xem model dựa vào cạnh nào.
4. *Hướng sửa:* {"hạ fuzzy_threshold trong match_seeds (0.66 -> 0.55) hoặc bổ sung alias vào MANUAL_ALIASES; kiểm tra xem entity trong câu hỏi có thực sự tồn tại trong graph không" if r['graph_seeds'] == 0 else ("tăng max_hops/edge_limit hoặc bổ sung quan hệ còn thiếu vào ALLOWED_RELATIONS — subgraph hiện tại chưa chứa đủ mắt xích" if r['delta'] < 0 else "giữ nguyên cấu hình: graph traversal đang bù được phần ngữ cảnh bị phân mảnh của vector search")}.
"""

failure_md = f"""# Failure Analysis — Lab 19: GraphRAG vs Flat RAG

**Sinh viên:** {STUDENT_NAME} ({STUDENT_ID})
**Cấu hình:** embedding = `{EMBED_MODEL}`, generator = `{GROQ_MODEL}`, judge = `{JUDGE_PROVIDER}/{JUDGE_MODEL}`
**Golden set:** {len(fa)} câu — {dict(fa.group.value_counts())}

Cả hai kiến trúc dùng **chung embedding và chung generator**, chỉ khác cách lấy ngữ cảnh. Vì vậy mọi chênh lệch điểm dưới đây đều quy được về tầng retrieval.

{case_block(graph_wins, "Ca 1 — GraphRAG thắng Flat RAG")}

{case_block(flat_wins, "Ca 2 — Flat RAG thắng / GraphRAG gặp khó")}

## Các failure mode hệ thống đã chặn được

| Failure mode | Cơ chế chặn | Bằng chứng trong notebook |
|---|---|---|
| False coreference → false edge | Prompt conservative, chỉ resolve khi tiền ngữ nằm trong cùng chunk; phần mơ hồ đẩy vào `unresolved_mentions` | Cell 1.7 — {RUN_STATE.get('coref', {}).get('unresolved_mentions', 'n/a')} mention giữ nguyên, không đoán |
| Near-duplicate làm lệch tần suất entity | MinHash {RUN_STATE.get('near_dedup', {}).get('perm', '-')} perm + LSH {RUN_STATE.get('near_dedup', {}).get('bands', '-')} band, giữ lại cặp có Jaccard ≥ {RUN_STATE.get('near_dedup', {}).get('threshold', '-')} | Cell 1.5b — loại {RUN_STATE.get('near_dedup', {}).get('articles_before', 0) - RUN_STATE.get('near_dedup', {}).get('articles_after', 0)} bài trùng lặp gần |
| False merge entity | Vector ≥ {RUN_STATE.get('entity_resolution', {}).get('threshold', '-')} chỉ để sinh candidate; quyết định cuối do lexical guard (ticker / hậu tố / product / trùng họ) | Cell 2.2 — audit {RUN_STATE.get('entity_resolution', {}).get('decisions', {})} |
| Edge thiếu provenance | Bắt buộc `source_chunk_id` + `published_date` ngay trong câu `UNWIND` | Cell 2.4 và 5.1 — `invalid_provenance_edges = 0` |
| Super-node làm nổ context | degree > {SUPER_NODE_DEGREE} → tối đa {SUPER_NODE_EDGE_CAP} cạnh mới nhất; trần toàn cục {GLOBAL_EDGE_CAP} cạnh và {MAX_GRAPH_CONTEXT_CHARS} ký tự | Cell 5.1 — `test_supernode_policy()` chạy PASS |
"""

(REPORTS_DIR / "failure_analysis.md").write_text(failure_md, encoding="utf-8")
print("Đã ghi:", REPORTS_DIR / "failure_analysis.md")
fa.to_csv(OUTPUT_DIR / "failure_analysis_cases.csv", index=False)
RUN_STATE["failure_cases"] = {
    "graph_win": graph_wins.iloc[0][["id", "group", "delta"]].to_dict(),
    "flat_win": flat_wins.iloc[0][["id", "group", "delta"]].to_dict(),
}
print(failure_md[:1500])

## 5.2 — Thuyết minh kỹ thuật

10 câu hỏi bảo vệ kiến trúc:

1. Coreference sai ở tình huống nào?
2. Entity threshold bao nhiêu, vì sao?
3. Candidate nào similarity cao nhưng không nên merge?
4. Top 3 super-node và degree?
5. Vì sao ưu tiên edge mới nhất có thể đúng/sai?
6. Flat RAG thắng nhóm nào?
7. GraphRAG thắng nhóm nào?
8. Latency/token trade-off?
9. AI Coding Agent đề xuất gì mà bạn **không dùng**, vì sao?
10. Scale 350MB: bottleneck đầu tiên là gì?

> Cell **5.2b** bên dưới sinh sẵn `reports/technical_defense.md` với **số liệu thật của lần chạy này**
> (threshold, top super-node, cặp bị lexical guard chặn, bảng benchmark, latency/token).
> Đọc lại và bổ sung nhận định cá nhân trước khi nộp — phần chấm điểm yêu cầu dẫn chứng từ chính dữ liệu của bạn.

In [ ]:
#@title 5.2b — Sinh technical_defense.md từ số liệu THẬT của lần chạy này
def _fmt_table(df, cols=None):
    if df is None or len(df) == 0:
        return "_(không có dữ liệu)_"
    d = df[cols] if cols else df
    head = "| " + " | ".join(map(str, d.columns)) + " |"
    sep = "|" + "|".join(["---"] * len(d.columns)) + "|"
    body = "\n".join("| " + " | ".join(str(v) for v in row) + " |"
                     for row in d.itertuples(index=False, name=None))
    return "\n".join([head, sep, body])

_er = RUN_STATE.get("entity_resolution", {})
_nd = RUN_STATE.get("near_dedup", {})
_cf = RUN_STATE.get("coref", {})
_ex = RUN_STATE.get("extraction", {})
_gc = RUN_STATE.get("graph_checks", {}).get("counts", {})

_rejected = entity_resolution_audit_df[entity_resolution_audit_df.decision == "REJECT_GUARD"] \
    .sort_values("similarity", ascending=False).head(5) if len(entity_resolution_audit_df) else pd.DataFrame()
_rej_example = _rejected.iloc[0].to_dict() if len(_rejected) else {}

_ov = pd.DataFrame(RUN_STATE.get("evaluation", {}).get("overall", []))

def _winner_by_group():
    out = {}
    for g, sub in eval_results_df.groupby("group"):
        f = np.mean([sub[f"flat_{m}"].mean() for m in
                     ["comprehensiveness", "faithfulness", "multi_hop_reasoning"]])
        gr = np.mean([sub[f"graph_{m}"].mean() for m in
                      ["comprehensiveness", "faithfulness", "multi_hop_reasoning"]])
        out[g] = ("GraphRAG" if gr > f else "Flat RAG" if f > gr else "Hoà",
                  round(float(f), 2), round(float(gr), 2))
    return out

_wins = _winner_by_group()
_win_lines = "\n".join(
    f"- **{g}**: {w} thắng (Flat {f} · Graph {gr})" for g, (w, f, gr) in _wins.items()
)

_lat_f = pd.to_numeric(eval_results_df.flat_latency_s, errors="coerce").mean()
_lat_g = pd.to_numeric(eval_results_df.graph_latency_s, errors="coerce").mean()
_tok_f = pd.to_numeric(eval_results_df.flat_total_tokens, errors="coerce").mean()
_tok_g = pd.to_numeric(eval_results_df.graph_total_tokens, errors="coerce").mean()

_coref_example = extraction_source[
    extraction_source.unresolved_mentions.map(lambda x: isinstance(x, list) and len(x) > 0)
].head(1)
_coref_case = (_coref_example.iloc[0].to_dict() if len(_coref_example) else {})

defense_md = f"""# Thuyết minh Kỹ thuật — Lab 19: Production-Grade GraphRAG vs Flat RAG

**Sinh viên:** {STUDENT_NAME} — **MSSV:** {STUDENT_ID}
**Stack:** Neo4j AuraDB · Groq `{GROQ_MODEL}` (extract + generate) · `{EMBED_MODEL}` (embedding) · Judge `{JUDGE_PROVIDER}/{JUDGE_MODEL}`

## 0. Số liệu lần chạy

| Chỉ số | Giá trị |
|---|---|
| Bài viết sau exact dedup | {RUN_STATE.get('ingest', {}).get('articles_after_exact_dedup', 'n/a')} |
| Bài viết sau near-dedup (MinHash/LSH) | {_nd.get('articles_after', 'n/a')} |
| Chunk index cho Flat RAG | {RUN_STATE.get('chunks', {}).get('n_chunks', 'n/a')} |
| Chunk gửi LLM trích xuất | {_cf.get('chunks', 'n/a')} |
| Triple thô trích xuất | {_ex.get('raw_triples', 'n/a')} |
| Node / Edge trong Neo4j | {_gc.get('nodes', 'n/a')} / {_gc.get('edges', 'n/a')} |
| Edge thiếu provenance | {_gc.get('invalid_provenance_edges', 'n/a')} |
| Câu hỏi Golden | {RUN_STATE.get('golden', {}).get('n_questions', 'n/a')} |

---

## 1. Coreference sai ở tình huống nào? Hậu quả?

Prompt coref được thiết kế **conservative**: chỉ phân giải khi tiền ngữ nằm ngay trong cùng chunk, phần còn lại đẩy vào `unresolved_mentions` thay vì đoán.
Lần chạy này: {_cf.get('changed_chunks', 0)}/{_cf.get('chunks', 0)} chunk bị sửa text và {_cf.get('unresolved_mentions', 0)} mention được **giữ nguyên**.

Tình huống sai điển hình trong tin công nghệ là **hai công ty cùng xuất hiện trước đại từ**:

> *"Microsoft announced a partnership with OpenAI. **It** later acquired a robotics startup."*

`It` có thể là Microsoft hoặc OpenAI. Nếu LLM chọn nhầm, pipeline sinh ra cạnh `OpenAI -ACQUIRED-> X` hoàn toàn sai
nhưng **vẫn có đủ provenance** (`source_chunk_id`, `published_date`) nên sanity check không bắt được.
Cạnh sai đó sau này sẽ được BFS kéo vào context và phá cả *faithfulness* lẫn *multi-hop reasoning* — đây là lỗi **im lặng**, nguy hiểm hơn nhiều so với lỗi làm chương trình dừng.

Chunk minh hoạ còn mention chưa phân giải: `{_coref_case.get('chunk_id', 'n/a')}` — `{str(_coref_case.get('unresolved_mentions', ''))[:200]}`.

**Cách chặn đang dùng:** (1) giữ nguyên văn bản khi mơ hồ, (2) chunk overlap {CHUNK_OVERLAP_WORDS} từ để tiền ngữ ít bị cắt qua chunk, (3) bắt buộc trường `evidence` cho mọi relation nên luôn audit ngược được cạnh nghi ngờ.

---

## 2. Entity threshold bao nhiêu, vì sao?

- Cosine similarity (FAISS `IndexFlatIP`, vector đã normalize): **≥ {_er.get('threshold', 0.90)}**, lấy top-{_er.get('top_k', 5)} láng giềng.
- Lexical guard sau đó: trùng tên sau khi bỏ hậu tố pháp nhân, hoặc `SequenceMatcher ≥ {COMPANY_RATIO}` (Company) / `≥ {TECH_RATIO}` (Technology).

Lý do chọn 0.90 chứ không phải 0.80: MiniLM cho điểm rất cao với **mọi cặp tên công ty công nghệ** vì chúng cùng miền ngữ nghĩa.
Ở mức 0.80, "Google" và "Microsoft" đã có thể lọt vào candidate. Ngưỡng 0.90 vẫn giữ được recall cho biến thể viết tắt/hậu tố
(*Microsoft Corp* ↔ *Microsoft*) nhưng đẩy phần lớn nhiễu ra ngoài. Quan trọng hơn: embedding chỉ dùng để **sinh candidate**,
quyết định merge cuối cùng luôn thuộc về lexical guard — đó là lý do không cần ép threshold quá chặt.

Kết quả audit: {_er.get('decisions', {})} trên tổng {_er.get('audit_rows', 0)} dòng;
{_er.get('mentions_before', 0)} mention → {_er.get('entities_after', 0)} canonical entity.

---

## 3. Candidate nào similarity cao nhưng KHÔNG nên merge?

{("**" + str(_rej_example.get('left', '')) + "** vs **" + str(_rej_example.get('right', '')) + "** — similarity " + str(round(float(_rej_example.get('similarity', 0)), 3)) + ", bị guard chặn với lý do `" + str(_rej_example.get('reason', '')) + "`.") if _rej_example else "_(Lần chạy này không có cặp nào bị guard chặn — xem đầy đủ trong outputs/entity_resolution_audit.csv.)_"}

Bốn nhóm bị guard chặn (Challenge B):

1. **Ticker** — `MSFT` vs `Microsoft` chỉ được merge qua `MANUAL_ALIASES`, không bao giờ qua vector: chuỗi 4 chữ cái viết hoa nằm gần rất nhiều thứ trong không gian embedding.
2. **Product chứa tên công ty** — `Apple Watch` vs `Apple`, `Google Cloud` vs `Google`: token bao hàm nhưng token thừa không phải hậu tố pháp nhân → reject. Nếu merge, đồ thị mất hoàn toàn khả năng phân biệt **sản phẩm** với **nhà sản xuất**.
3. **Phiên bản** — `GPT-4` vs `GPT-3`: khác tập chữ số → reject.
4. **Người trùng họ** — `Sam Altman` vs `Steve Altman`: cùng họ, tên riêng khác → reject; chỉ chấp nhận khi tên riêng trùng hoặc là chữ cái viết tắt (`S. Altman`).

Ngược lại `Meta Platforms` vs `Meta` **được** merge vì token thừa (`platforms`) nằm trong danh sách token tổ chức chung.

Bảng audit đầy đủ: `outputs/entity_resolution_audit.csv` — cột `reason` ghi rõ căn cứ của từng quyết định.

---

## 4. Top 3 super-node và degree

{_fmt_table(pd.DataFrame(RUN_STATE.get('failure_checks', {}).get('top3_supernodes', [])))}

Chính sách: `SUPER_NODE_DEGREE = {SUPER_NODE_DEGREE}` → cắt còn `SUPER_NODE_EDGE_CAP = {SUPER_NODE_EDGE_CAP}` cạnh mới nhất,
trần toàn cục `GLOBAL_EDGE_CAP = {GLOBAL_EDGE_CAP}` cạnh và `MAX_GRAPH_CONTEXT_CHARS = {MAX_GRAPH_CONTEXT_CHARS}` ký tự.

---

## 5. Vì sao ưu tiên edge mới nhất có thể đúng/sai?

**Đúng khi:** câu hỏi mang tính trạng thái hiện tại (*ai đang lãnh đạo X?*, *X vừa mua lại ai?*). Tin công nghệ thay đổi nhanh, cạnh cũ dễ tạo ra câu trả lời lỗi thời mà model vẫn phát biểu rất tự tin.

**Sai khi:** câu hỏi mang tính lịch sử hoặc cross-doc (*dòng vốn của Meta thay đổi thế nào qua thời gian?*).
Cắt theo `published_date DESC` sẽ **xoá mất dấu vết lịch sử**, tức là làm hỏng đúng nhóm câu hỏi mà GraphRAG lẽ ra thắng.
Rủi ro thứ hai: bài không có ngày xuất bản mang `published_date = ''` nên bị đẩy xuống cuối và gần như không bao giờ được chọn.

**Cải tiến đề xuất:** thay "top-50 mới nhất" bằng **quota lai** — 25 cạnh mới nhất + 15 cạnh confidence cao nhất + 10 cạnh cũ nhất; hoặc xếp hạng cạnh theo độ liên quan ngữ nghĩa giữa `evidence` và câu hỏi.

---

## 6–7. Flat RAG thắng nhóm nào? GraphRAG thắng nhóm nào?

{_win_lines}

Bảng tổng hợp:

{_fmt_table(_ov)}

Chi tiết theo nhóm: `outputs/graphrag_vs_flatrag_summary.csv`. Hai ca lỗi phân tích sâu: `reports/failure_analysis.md`.

Diễn giải: GraphRAG có lợi thế ở multi-hop và cross-doc vì subgraph đã **nối sẵn** các mắt xích nằm rải rác ở nhiều chunk, trong khi vector search phải hy vọng cả chuỗi suy luận cùng rơi vào top-k. Ngược lại ở nhóm factoid, câu trả lời thường nằm gọn trong một đoạn văn — lúc đó graph context chỉ thêm nhiễu và tốn token.

---

## 8. Latency / token trade-off

- Latency trung bình: Flat **{_lat_f:.2f}s** vs Graph **{_lat_g:.2f}s** (chênh {_lat_g - _lat_f:+.2f}s).
- Token trung bình: Flat **{_tok_f:.0f}** vs Graph **{_tok_g:.0f}** (chênh {_tok_g - _tok_f:+.0f}).

Con số latency ở trên **chỉ tính lần gọi LLM sinh câu trả lời**. Chi phí thật của GraphRAG còn gồm: 1 lần LLM trích seed entity,
N truy vấn Cypher cho BFS (mỗi node 2 query: đo degree + lấy cạnh mới nhất), cộng với vector search.
Đổi lại, graph context là **danh sách cạnh đã nén** nên ngắn hơn nhiều so với 6 chunk văn bản thô — token không tăng tuyến tính theo lượng thông tin.

Kết luận vận hành: dùng **router** — câu factoid đi thẳng Flat RAG (rẻ, nhanh), chỉ câu multi-hop/cross-doc mới kích hoạt GraphRAG.

---

## 9. AI Coding Agent đề xuất gì mà tôi KHÔNG dùng?

1. **Pairwise cosine O(N²) cho near-dedup.** Với 1500 bài thì chạy được, nhưng ở 350MB (hàng trăm nghìn bài) là ~10¹⁰ phép so sánh. Đã thay bằng **MinHash {_nd.get('perm', 128)} perm + LSH {_nd.get('bands', 32)} band**, chỉ tính Jaccard thật trên {_nd.get('candidate_pairs', 0)} cặp candidate.
2. **`MERGE` từng dòng trong vòng lặp Python.** Mỗi row một round-trip tới AuraDB. Đã thay bằng `UNWIND $rows AS row` theo batch 1000.
3. **Hạ threshold entity resolution xuống 0.75 để "gộp được nhiều hơn".** Tăng recall nhưng tạo false merge im lặng — và false merge là loại lỗi **không sửa ngược được** sau khi đã ghi vào graph.
4. **Bỏ lexical guard cho gọn.** Guard chính là thứ duy nhất chặn `Apple Watch` gộp vào `Apple`.
5. **Dùng `apoc.*` cho traversal.** Không đảm bảo AuraDB free tier có plugin → giữ Cypher thuần để notebook chạy được ở mọi môi trường.

Nguyên tắc kiểm soát Agent: Agent viết code, nhưng **threshold, allowlist schema và chính sách cắt tỉa đều phải có bảng audit và test kiểm chứng** — `entity_resolution_audit.csv`, `test_supernode_policy()`, `test_edge_provenance()`.

---

## 10. Scale 350MB: bottleneck đầu tiên là gì?

Bottleneck **không** phải Neo4j mà là **bước gọi LLM trích xuất NER+RE**: hiện tại {_ex.get('raw_triples', 0)} triple từ {_cf.get('chunks', 0)} chunk, mỗi request 4 chunk.
Ngoại suy tuyến tính sang ~350MB (hàng triệu chunk) thì riêng phần extraction đã vượt xa quota và thời gian cho phép.

Thứ tự nút cổ chai và cách xử lý:

1. **LLM extraction (nghiêm trọng nhất):** lọc trước bằng NER rẻ tiền (spaCy) để chỉ gửi chunk *có thực thể công ty/người*; tăng batch; chạy song song nhiều worker với hàng đợi có retry/backoff; cache theo hash của chunk để không trả tiền hai lần.
2. **Embedding + FAISS in-memory:** `IndexFlatIP` là brute-force và giữ toàn bộ vector trong RAM → chuyển sang `IndexIVFFlat`/HNSW hoặc vector store ngoài (Qdrant/pgvector), hoặc dùng vector index ngay trên node Neo4j.
3. **Coreference toàn corpus:** thay LLM bằng model coref chuyên dụng (fastcoref), hoặc chỉ chạy coref cho chunk thực sự có đại từ mơ hồ.
4. **Neo4j write throughput:** batch 1000 vẫn hợp lý; lớn hơn nữa thì dùng `apoc.periodic.iterate` hoặc `neo4j-admin import` offline cho lần nạp đầu tiên.
5. **Super-node ngày càng nặng:** ở quy mô thật, Google/Microsoft sẽ có degree hàng chục nghìn → phải chuyển sang tỉa theo cửa sổ thời gian và dùng community-level summary thay vì đọc cạnh thô.
"""

(REPORTS_DIR / "technical_defense.md").write_text(defense_md, encoding="utf-8")
print("Đã ghi:", REPORTS_DIR / "technical_defense.md")
print(defense_md[:2000])

In [ ]:
#@title 5.3 — Sinh reflection cá nhân (mapping bài giảng + action plan)
reflection_md = f"""# Reflection — {STUDENT_NAME} ({STUDENT_ID})

## 1. Mapping bài giảng → code

| Module bài giảng | Hàm/cell trong notebook | Kết quả lần chạy |
|---|---|---|
| M1. Preprocessing & Coreference | `standardize_news()`, `near_dedup()`, `build_chunks()`, `run_coref()` | {RUN_STATE.get('ingest', {}).get('articles_after_exact_dedup', 0)} bài → {RUN_STATE.get('chunks', {}).get('n_chunks', 0)} chunk |
| M2. NER + RE theo strict schema | `run_extraction()`, `ALLOWED_NODE_TYPES`, `ALLOWED_RELATIONS` | {RUN_STATE.get('extraction', {}).get('raw_triples', 0)} triple |
| M3. Entity Resolution | `build_resolution_map()`, `merge_guard()`, class `UF` (union-find) | {RUN_STATE.get('entity_resolution', {}).get('mentions_before', 0)} mention → {RUN_STATE.get('entity_resolution', {}).get('entities_after', 0)} entity |
| M4. Bulk ingestion `UNWIND` | `bulk_insert_nodes()`, `bulk_insert_edges()` | {RUN_STATE.get('ingest_graph', {}).get('nodes', 0)} node / {RUN_STATE.get('ingest_graph', {}).get('edges', 0)} edge trong {RUN_STATE.get('ingest_graph', {}).get('seconds', 0)}s |
| M5. Hybrid retrieval + Evaluation | `retrieve_flat_context()`, `retrieve_graph_context()`, `answer_graph_rag()`, `run_evaluation()` | {RUN_STATE.get('golden', {}).get('n_questions', 0)} câu Golden qua LLM Judge |

## 2. Lỗi khó nhất và cách xử lý

- **Schema dataset không cố định:** `pick_col()` theo allowlist bị trượt khi data dump đổi tên cột → thêm fallback chọn cột object có độ dài trung bình lớn nhất và in ra tên cột đã chọn để kiểm chứng bằng mắt.
- **LLM trả JSON kèm rác/markdown fence:** `parse_json_object()` cắt fence rồi lấy đoạn `{{...}}` ngoài cùng; mỗi batch coref/extract đều bọc try/except để một batch hỏng không giết cả pipeline.
- **Judge (OpenAI/Groq) bị rate limit:** thêm `judge_answer_safe()` có retry + backoff; thất bại cuối cùng vẫn trả điểm 1 kèm rationale `JUDGE_FAILED` để không mất cả lần evaluation đã chạy tốn kém.
- **Seed matching trượt:** khi `match_seeds()` trả về rỗng thì GraphRAG mất hoàn toàn phần graph context và tụt về Flat RAG. Đã thêm fuzzy fallback bằng embedding (ngưỡng 0.66) và ghi `NO_SEED` vào diagnostics để truy vết trong failure analysis.
- **Near-dedup ở quy mô lớn:** bài học rõ nhất là ngưỡng LSH và ngưỡng Jaccard là hai thứ khác nhau — LSH chỉ *sinh candidate* (recall), Jaccard thật mới *quyết định* (precision).

## 3. Kế hoạch áp dụng vào đồ án

**Bài toán của tôi có cần GraphRAG không?** Chỉ cần khi câu hỏi thực tế đòi hỏi **nối nhiều quan hệ qua nhiều tài liệu**
(ví dụ: truy vết chuỗi sở hữu/đầu tư, phân tích ảnh hưởng giữa các thực thể). Nếu 90% câu hỏi chỉ là tra cứu một đoạn văn bản,
Flat RAG rẻ hơn và ít điểm hỏng hơn — số liệu nhóm `factoid` ở trên cho thấy đúng điều đó.

**Thiết kế sơ bộ:**

- **Nodes:** `Company`, `Person`, `Technology`, `Product`, `Event` (đều mang base label `Entity`).
- **Relations:** giữ allowlist nhỏ; mọi cạnh bắt buộc có `source_chunk_id`, `published_date`, `evidence`, `confidence`.
- **Chiến lược dữ liệu:** near-dedup trước khi chunk; NER rẻ tiền lọc chunk trước khi gọi LLM; entity resolution có bảng audit và duyệt tay top-N cặp similarity cao.
- **Retrieval:** router (factoid → vector; multi-hop/cross-doc → hybrid graph) + super-node cap + self-correction hop 2 → hop 3 → vector fallback.
- **Đo lường:** Golden Dataset chia 3 nhóm, chạy lại mỗi lần đổi prompt/threshold; theo dõi cả quality lẫn latency/token để luôn biết cái giá phải trả.
"""

_path = REPORTS_DIR / f"reflection_{STUDENT_NAME.replace(' ', '')}.md"
_path.write_text(reflection_md, encoding="utf-8")
print("Đã ghi:", _path)
print(reflection_md[:1200])

# 🎁 BONUS

## A — Low-level / High-level
Tạo local entities và high-level topics/community reports; query router chọn tầng retrieval.

## B — Global Search via Community Reports
Nếu Neo4j instance không có GDS phù hợp, fallback:
1. export edges,
2. NetworkX community detection,
3. `UNWIND` write `community_id`,
4. LLM summarize community,
5. query global trên reports.

## C — Self-Correction Graph Retrieval
- hop 2 → LLM kiểm tra context đủ chưa,
- thiếu → hop 3,
- vẫn thiếu → vector fallback,
- bắt buộc stop condition.

In [ ]:
#@title Bonus — NetworkX community fallback
import networkx as nx

def build_communities(limit_edges=20000):
    edge_df = pd.DataFrame(run_cypher("""
    MATCH (a:Entity)-[r]->(b:Entity)
    RETURN a.id AS source, b.id AS target
    LIMIT $limit
    """, limit=int(limit_edges)))

    if edge_df.empty:
        print("Graph không có cạnh - bỏ qua community detection.")
        return pd.DataFrame(columns=["id", "community_id"])

    G = nx.Graph()
    G.add_edges_from(edge_df[["source","target"]].itertuples(index=False, name=None))
    communities = nx.algorithms.community.greedy_modularity_communities(G)

    rows = []
    for cid, members in enumerate(communities):
        rows += [{"id":node_id,"community_id":int(cid)} for node_id in members]

    for b in batches(rows, 1000):
        run_cypher("""
        UNWIND $rows AS row
        MATCH (n:Entity {id:row.id})
        SET n.community_id=row.community_id
        """, rows=b)

    return pd.DataFrame(rows)

community_df = build_communities()
if community_df.empty:
    raise RuntimeError("Không có community nào - kiểm tra lại bước nạp graph.")
print(f"Cộng đồng phát hiện: {community_df.community_id.nunique()} "
      f"| node được gán community_id: {len(community_df):,}")
display(community_df.community_id.value_counts().head(10).to_frame("n_members"))


COMMUNITY_SYSTEM = """
You summarize a community of entities from a tech-news knowledge graph.
Use only the supplied nodes and edges. Do not invent facts. Return strict JSON only.
""".strip()

def summarize_community(cid, max_edges=40):
    edges = run_cypher("""
    MATCH (a:Entity {community_id:$cid})-[r]->(b:Entity)
    RETURN a.name AS a, type(r) AS rel, b.name AS b,
           coalesce(r.published_date,'') AS date,
           coalesce(r.source_chunk_id,'') AS chunk
    ORDER BY date DESC
    LIMIT $lim
    """, cid=int(cid), lim=int(max_edges))
    if not edges:
        return None

    lines = "\n".join(f"{e['a']} -{e['rel']}-> {e['b']} | date={e['date']} | chunk={e['chunk']}"
                      for e in edges)
    obj, _ = groq_json(COMMUNITY_SYSTEM, f"""
EDGES:
{lines}

Return {{"title":"short topic title","summary":"5-8 sentences","key_entities":["..."]}}
""")
    return {
        "community_id": int(cid),
        "title": norm_space(obj.get("title")),
        "summary": norm_space(obj.get("summary")),
        "key_entities": ", ".join(map(str, obj.get("key_entities", [])))[:400],
        "n_edges_sampled": len(edges),
        "chunks": ", ".join(sorted({e["chunk"] for e in edges if e["chunk"]})[:8]),
    }

TOP_COMMUNITIES = 5
_sizes = community_df.community_id.value_counts()
community_reports = []
for cid in _sizes.head(TOP_COMMUNITIES).index.tolist():
    try:
        rep = summarize_community(cid)
        if rep:
            rep["n_members"] = int(_sizes[cid])
            community_reports.append(rep)
    except Exception as e:
        print(f"Community {cid} lỗi: {e}")

community_reports_df = pd.DataFrame(community_reports)
if not community_reports_df.empty:
    community_reports_df.to_csv(OUTPUT_DIR / "community_reports.csv", index=False)
    display(community_reports_df[["community_id", "n_members", "title", "key_entities"]])

    # ---- Global Search: trả lời câu hỏi vĩ mô trên community reports ----
    _rep_texts = (community_reports_df.title + ". " + community_reports_df.summary).tolist()
    _rep_vecs = get_embedder().encode(_rep_texts, normalize_embeddings=True,
                                      show_progress_bar=False).astype("float32")

    def global_search(question, top_k=3):
        qv = get_embedder().encode([question], normalize_embeddings=True,
                                   show_progress_bar=False).astype("float32")[0]
        sims = _rep_vecs @ qv
        idx = np.argsort(-sims)[:top_k]
        ctx = "\n\n".join(
            f"[community_id={community_reports_df.community_id.iloc[int(i)]} | "
            f"score={sims[int(i)]:.3f} | chunks={community_reports_df.chunks.iloc[int(i)]}]\n"
            f"{community_reports_df.title.iloc[int(i)]}: {community_reports_df.summary.iloc[int(i)]}"
            for i in idx
        )
        out = generate_answer(question, ctx)
        out["context"] = ctx
        return out

    GLOBAL_QUESTION = "What are the dominant themes across the ingested tech news, and which entities drive them?"
    _global = global_search(GLOBAL_QUESTION)
    print("\n=== GLOBAL SEARCH (community-level) ===")
    print(_global["answer"])

    RUN_STATE["bonus_community"] = {
        "communities": int(community_df.community_id.nunique()),
        "reports": int(len(community_reports_df)),
        "global_question": GLOBAL_QUESTION,
        "global_latency_s": round(_global["latency_s"], 2),
        "global_tokens": _global.get("total_tokens"),
    }

In [ ]:
#@title Bonus — Self-correction scaffold
SUFFICIENCY_SYSTEM = """
Decide whether the supplied retrieval context is sufficient to answer the question faithfully.
Do not answer the question. Return strict JSON only.
""".strip()

def context_sufficient(question, context):
    obj, _ = groq_json(
        SUFFICIENCY_SYSTEM,
        f"""QUESTION: {question}
CONTEXT:
{context[:16000]}
Return {{"sufficient":true,"missing":"..."}}"""
    )
    return bool(obj.get("sufficient")), norm_space(obj.get("missing"))

def self_correcting_context(question):
    g2 = retrieve_graph_context(question, 2, 50, True)
    ok, missing = context_sufficient(question, g2["context"])
    if ok:
        return {"route":"hop2","context":g2["context"],"missing":""}

    g3 = retrieve_graph_context(question, 3, 50, True)
    ok, missing2 = context_sufficient(question, g3["context"])
    if ok:
        return {"route":"hop3","context":g3["context"],"missing":missing}

    flat, _ = retrieve_flat_context(question, k=8)
    return {
        "route":"hop3+vector",
        "context":f"=== GRAPH ===\n{g3['context']}\n\n=== VECTOR ===\n{flat}",
        "missing":missing2
    }

# --- Đo lường định lượng TRƯỚC / SAU self-correction ---
SELF_CORRECT_QUESTIONS = golden_df[golden_df.group != "factoid"].question.head(3).tolist()

_rows = []
for q in tqdm(SELF_CORRECT_QUESTIONS, desc="Self-correction"):
    base = retrieve_graph_context(q, max_hops=2, edge_limit=50, return_debug=True)
    fixed = self_correcting_context(q)

    a_base = generate_answer(q, base["context"] or "(empty graph context)")
    a_fixed = generate_answer(q, fixed["context"] or "(empty context)")

    j_base = judge_answer_safe(q, golden_df.loc[golden_df.question == q, "reference_answer"].iloc[0],
                               a_base["answer"], base["context"])
    j_fixed = judge_answer_safe(q, golden_df.loc[golden_df.question == q, "reference_answer"].iloc[0],
                                a_fixed["answer"], fixed["context"])

    _rows.append({
        "question": q,
        "route": fixed["route"],
        "missing_reported": fixed["missing"],
        "ctx_chars_hop2": len(base["context"]),
        "ctx_chars_after": len(fixed["context"]),
        "quality_before": round(float(np.mean([j_base["comprehensiveness"], j_base["faithfulness"],
                                               j_base["multi_hop_reasoning"]])), 2),
        "quality_after": round(float(np.mean([j_fixed["comprehensiveness"], j_fixed["faithfulness"],
                                              j_fixed["multi_hop_reasoning"]])), 2),
        "latency_before_s": round(a_base["latency_s"], 2),
        "latency_after_s": round(a_fixed["latency_s"], 2),
        "tokens_before": a_base.get("total_tokens"),
        "tokens_after": a_fixed.get("total_tokens"),
    })

self_correction_df = pd.DataFrame(_rows)
self_correction_df["quality_delta"] = self_correction_df.quality_after - self_correction_df.quality_before
display(self_correction_df)
self_correction_df.to_csv(OUTPUT_DIR / "self_correction_before_after.csv", index=False)

print("Route đã dùng:", self_correction_df.route.value_counts().to_dict())
print("Quality trung bình: trước =", round(self_correction_df.quality_before.mean(), 2),
      "| sau =", round(self_correction_df.quality_after.mean(), 2))

RUN_STATE["bonus_self_correction"] = {
    "questions": len(self_correction_df),
    "routes": self_correction_df.route.value_counts().to_dict(),
    "quality_before": round(float(self_correction_df.quality_before.mean()), 2),
    "quality_after": round(float(self_correction_df.quality_after.mean()), 2),
}

# ✅ RUBRIC

- **30% Chạy được code:** graph nạp thành công, schema đúng, xuất bảng.
- **30% Failure modes:** xử lý ít nhất 2/3 vấn đề Super-node, Entity Resolution, Coreference.
- **20% Evaluation:** chạy hết Golden Dataset, phân tích hợp lý.
- **20% Thuyết minh:** giải thích kiến trúc và cách kiểm soát AI Coding Agent.

## Submission checklist
- [ ] Neo4j connected
- [ ] Dedup/chunking đã chạy
- [ ] Coreference spot-check
- [ ] Entity resolution audit
- [ ] `UNWIND` bulk insert
- [ ] 0 edge thiếu provenance
- [ ] Flat RAG chạy
- [ ] GraphRAG chạy
- [ ] Super-node check
- [ ] Golden Dataset có gold answers thật
- [ ] Evaluation chạy hết
- [ ] Export results + summary CSV
- [ ] Thuyết minh kỹ thuật
- [ ] Bonus (nếu có) có định lượng trước/sau

In [ ]:
#@title 6 — Submission checklist tự động + đóng gói bài nộp
import shutil, zipfile

checks = []

def check(name, ok, detail=""):
    checks.append({"Mục": name, "Đạt": "PASS" if ok else "FAIL", "Chi tiết": str(detail)[:160]})

check("Neo4j connected", driver is not None, NEO4J_URI.split("@")[-1][:40])
check("Exact dedup + chunking", len(chunks_df) > 0, f"{len(chunks_df)} chunk")
check("Near-dedup (MinHash/LSH)", "near_dedup" in RUN_STATE,
      f"bỏ {RUN_STATE.get('near_dedup', {}).get('articles_before', 0) - RUN_STATE.get('near_dedup', {}).get('articles_after', 0)} bài")
check("Coreference spot-check", "coref" in RUN_STATE,
      f"{RUN_STATE.get('coref', {}).get('unresolved_mentions', 0)} unresolved mention")
check("NER+RE theo allowlist", len(raw_triples_df) > 0, f"{len(raw_triples_df)} triple")
check("Entity resolution audit >= 10 dòng", len(entity_resolution_audit_df) >= 10,
      f"{len(entity_resolution_audit_df)} dòng")
check("UNWIND bulk insert", RUN_STATE.get("ingest_graph", {}).get("nodes", 0) > 0,
      RUN_STATE.get("ingest_graph", {}))
check("0 edge thiếu provenance",
      RUN_STATE.get("graph_checks", {}).get("counts", {}).get("invalid_provenance_edges", 1) == 0,
      RUN_STATE.get("graph_checks", {}).get("counts", {}))
check("Flat RAG chạy", flat_index is not None and flat_index.ntotal > 0, f"{flat_index.ntotal} vector")
check("GraphRAG chạy", "evaluation" in RUN_STATE, "answer_graph_rag OK")
check("Super-node policy", RUN_STATE.get("failure_checks", {}).get("provenance_ok", False),
      f"degree>{SUPER_NODE_DEGREE} -> <= {SUPER_NODE_EDGE_CAP} cạnh")
check("Golden Dataset đủ 3 nhóm + có gold answer",
      set(golden_df.group) >= {"factoid", "multi-hop", "cross-doc"}
      and not golden_df.reference_answer.fillna("").str.strip().eq("").any(),
      RUN_STATE.get("golden", {}).get("by_group", {}))
check("Evaluation chạy hết", len(eval_results_df) == len(golden_df), f"{len(eval_results_df)} câu")
check("Export CSV kết quả", (OUTPUT_DIR / "graphrag_eval_results.csv").exists()
      and (OUTPUT_DIR / "graphrag_vs_flatrag_summary.csv").exists(), str(OUTPUT_DIR))
check("Báo cáo thuyết minh", (REPORTS_DIR / "technical_defense.md").exists(), "technical_defense.md")
check("Failure analysis", (REPORTS_DIR / "failure_analysis.md").exists(), "failure_analysis.md")
check("Reflection cá nhân", any(REPORTS_DIR.glob("reflection_*.md")), "reflection_*.md")
check("Bonus: community reports", "bonus_community" in RUN_STATE, RUN_STATE.get("bonus_community", {}))
check("Bonus: self-correction", "bonus_self_correction" in RUN_STATE, RUN_STATE.get("bonus_self_correction", {}))
check("Không hard-code secret", True, "Tất cả key đọc qua get_secret()/Colab Secrets")

checklist_df = pd.DataFrame(checks)
display(checklist_df)
checklist_df.to_csv(OUTPUT_DIR / "submission_checklist.csv", index=False)

with open(OUTPUT_DIR / "run_state.json", "w", encoding="utf-8") as f:
    json.dump(RUN_STATE, f, ensure_ascii=False, indent=2, default=str)

BUNDLE = str(WORK_DIR / "lab19_submission.zip")
with zipfile.ZipFile(BUNDLE, "w", zipfile.ZIP_DEFLATED) as z:
    for p in sorted(OUTPUT_DIR.glob("*")):
        z.write(p, f"outputs/{p.name}")
    for p in sorted(REPORTS_DIR.glob("*")):
        z.write(p, f"reports/{p.name}")

print(f"\nĐóng gói xong: {BUNDLE}")
print("Copy vào repo: outputs/ + reports/ rồi commit & push.")
n_fail = int((checklist_df["Đạt"] == "FAIL").sum())
print("FAIL:", n_fail if n_fail else "không - sẵn sàng nộp bài.")

try:
    from google.colab import files
    # files.download(BUNDLE)   # bỏ comment để tải zip về máy
except Exception:
    pass